require('multilinetrigger')
trigger=MultilineTrigger('psnd("Rune/Harden.ogg")','Runenschmiede')
trigger:Line("Du haertest den Rohling wieder und wieder, damit er spaeter den magischen",false,true)
trigger:Line("Energien beim Gravieren standhalten kann.",false,true)
trigger:Inject()
trigger=MultilineTrigger('psnd("Rune/Hammer1.ogg")','Runenschmiede')
trigger:Line("Mit Deinem Schmiedehammer und einem kleinen Stichel ziehst Du die Zeichnung.*",true,true)
trigger:Line(".*Rune auf .* nach\.",true,true)
trigger:Inject()
trigger=MultilineTrigger('psnd("Smith/hammer1.ogg")')
trigger:Line("Mit einem lauten Knall laesst .* Schmiedehammer .*",true,true)
trigger:Line("niedersausen.",false,true)
trigger:Inject()
trigger=MultilineTrigger('psnd("Rune/EngraveCorrect.ogg")','Runenschmiede')
trigger:Line("Noch ein paar Feinkorrekturen, sonst wirkt die Rune am Ende gar nicht wie",false,true)
trigger:Line("sie soll!",false,true)
trigger:Inject()
trigger=MultilineTrigger('psnd("Rune/Hammer2.ogg")','Runenschmiede')
trigger:Line("Du kommst ins Schwitzen, es ist ganz schoen anstrengend, mit so einem",false,true)
trigger:Line("grossen Hammer so fein dosierte Schlaege auf den Stichel auszufuehren.",false,true)
trigger:Inject()