speedwalklist={}
speedwalklist.min_dhun="n n n o n o o no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no nw no n no n no o o o o o so o o no o o o o so o so oeffne_tor s s s s s s sw s s s s s sw s"
speedwalklist.dhun_min="n no n n n n n no n n n n n oeffne_tor n nw w nw w w w w sw w w nw w w w w w sw s sw s sw so sw sw s s s so s so s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw w w s w s s s"
speedwalklist.cor_us="s sw w sw w sw sw sw sw sw sw sw sw w sw w w nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no nw no n no n"
speedwalklist.dk_uw="n n n n n no no no o o no no no n no n n n n n n no no no no no no no nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so s so so so so so so so o o o so o o o o no no o"
speedwalklist.gol_affe="o o o o o o o o o o o o o o no o o no n n n nw w sw n"
speedwalklist.gol_mine="nw w sw so so o so so o so o o so so o o o o so o so o o o o o o no nw"
speedwalklist.ker_run="no o s s s s s s s s w w w w w"
speedwalklist.ker_mos="so so o"
speedwalklist.ker_amp="no o no o so o o n no n nw n n nw w w sw w w nw no no o o o no o o o o o no no"
speedwalklist.kap_uw="s s s o o o o so o o o o o o no o so o o no o o o o o o o so so o o o so o so o so so s s s sw sw sw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.jer_los="w w w w w w w w w w w w"
speedwalklist.cor_min="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s sw w w w w sw s w w w s s s"
speedwalklist.camp_uw="nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so s so so so so so so so o o o so o o o o no no o"
speedwalklist.uw_dk="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so sw sw sw sw sw sw sw s s s s s s sw s sw sw sw w w sw sw sw s s s s s"
speedwalklist.bank_wal="s s w w w w w w w w w w w w w w s s s s s o o o o o o o o o o o s"
speedwalklist.aug_amp="o o o o o so o o so o o no o o o n o o o no no o o o no o o o o o no no"
speedwalklist.uw_kap="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o no no no n n n nw nw w nw w nw w w w nw nw w w w w w w w sw w w nw w sw w w w w w w nw w w w w n n n"
speedwalklist.uw_jas="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw so s s s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.jer_haf="s s s so o o o o"
speedwalklist.jas_uw="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n n n nw no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.uw_camp="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so"
speedwalklist.hol_lim="o o s s sw sw w w sw w w sw w nw w sw sw w sw w w sw w w sw so o o o o so so o no"
speedwalklist.us_uw="no o o o o o so o o no o o o o so o so oeffne_tor s s s s s s sw s s s s w nw nw w nw nw nw no nw n n nw w sw w"
speedwalklist.hol_her="o o s s sw sw w w sw w w sw w nw w sw sw w sw w w sw w w nw"
speedwalklist.her_hol="so o o no o o no o no no o so o no o o no o o no no n n w w"
speedwalklist.ash_us="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw no no no no no no n nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.ash_san="n sw sw sw sw w sw w w w w w w w w w w nw w w w nw nw n"
speedwalklist.ash_min="n sw sw sw sw w sw w w w w w w w w w w nw w w w nw nw n w nw w w nw nw nw w nw w w nw nw nw nw nw nw n nw n nw w w w w nw w w w nw nw w w nw w w w w w w w nw w w w s s s"
speedwalklist.ash_alo="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw no no no no no no n no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.arg_ruw="no n no o so o so so o so o no o o o no o so o no o o no o so so so so so s s sw sw so so sw so s s"
speedwalklist.us_min="s sw s sw so sw sw s s s so s so s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw w w s w s s s"
speedwalklist.us_cor="s sw s sw so sw sw s s s so s so s s s s s s s sw so so o so so s so so o o no o no no no no no no no no o no o no n"
speedwalklist.us_ash="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so s sw sw sw sw sw sw so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.us_alo="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.us_abt="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no n kletter_n kletter_no kletter_no no n kletter_n kletter_n kletter_n n"
speedwalklist.amp_ker="sw sw w w w w w sw w w w sw sw so o o no o o so s s so s sw s w w nw w sw w sw"
speedwalklist.amp_haf="sw sw w w w w w sw w w w sw sw so o o no o o no o o o o o o o o o o o o o o"
speedwalklist.amp_aug="sw sw w w w w w sw w w w sw sw w w w s w w w sw w w nw w w nw w w w w w"
speedwalklist.alo_us="w w w w w w sw w w w w w w w w w w w w w w sw nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.alo_san="w w w w w w sw w w w w w w w w w w w w w w sw s sw sw sw sw sw sw so so s s so s s s s s s s so so s s s so so so so so o so o o so o so sw sw sw sw w sw w w w w w w w w w w nw w w w nw nw n"
speedwalklist.mine_gol="so sw w w w w w w nw w nw w w w w nw nw w w nw w nw nw w nw nw no o so"
speedwalklist.wl_tin="o s s s s s s s s s s s s s s s s s"
speedwalklist.tin_wl="n n n n n n n n n n n n n n n n n w"
speedwalklist.tin_gwen="so o o o o so o o so o o o o so o o o o o so o so o o o o o o o o o o o n"
speedwalklist.skal_uw="no n no o no nw nw no o o o no n no no no no no no no no no n no no n no no no no n no n no n n n no no n n nw nw nw n n nw nw n nw n nw n nw n nw nw nw nw n n n nw w w w w nw nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so s so so so so so so so o o o so o o o o no no o"
speedwalklist.schmied_wal="n n n n n n n n n n o o o o o o o o o o o o o o o o o o o o n n n n n w w w w w w w w w w w n"
speedwalklist.san_min="w nw w w nw nw nw w nw w w nw nw nw nw nw nw n nw n nw w w w w nw w w w nw nw w w nw w w w w w w w n w w w w s s s"
speedwalklist.alo_min="w w w w w w sw w w w w w w w w w w w w w w sw s sw sw sw sw sw sw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw sw w w w w sw s w w w s s s"
speedwalklist.alo_ash="w w w w w w sw w w w w w w w w w w w w w w sw s sw sw sw sw sw sw so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.ale_los="w w n no n n nw n n n no n nw w w nw nw nw w w nw nw no nw n n n w w w w w w w w w w w w"
speedwalklist.wal_bank="n w w w w w w w w w w w n n n n n o o o o o o o o o o o o o o n n"
speedwalklist.abt_us="s kletter_s kletter_s kletter_s s sw kletter_sw kletter_sw kletter_s s sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.ver_los="no o o o no no no no no no no no n n no n n nw n n n no n nw w w nw nw nw w w nw nw no nw n n n w w w w w w w w w w w w"
speedwalklist.abt_min="s kletter_s kletter_s kletter_s s sw kletter_sw kletter_sw kletter_s s sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w sw sw s s s so s so s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw s w w w s s s"
speedwalklist.uw_us="o no o so s s so sw so so so o so so o n n n n no n n n n n oeffne_tor n nw w nw w w w w sw w w nw w w w w w sw"
speedwalklist.uw_skal="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so so o o o o so s s s so so so so s so s so s so s so so s s so so so s s sw sw s s s sw s sw s sw sw sw sw s sw sw s sw sw sw sw sw sw sw sw sw s sw w w w sw so so sw w sw s sw"
speedwalklist.uw_por="w sw sw w w w w nw w w w nw nw nw nw w w w w w w w w w w w w w w"
speedwalklist.san_alo="s so so o o o so o o o o o o o o o o no o no no no no nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw no no no no no no n no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.san_ash="s so so o o o so o o o o o o o o o o no o no no no no s"
speedwalklist.ruw_arg="n n nw no nw nw no no n n nw nw nw nw nw w sw w w sw w nw w sw w w w sw w nw w nw nw w nw w sw s sw"
speedwalklist.run_ker="o o o o o n n n n n n n n w sw"
speedwalklist.ril_por="sw s s s o o s s s sw sw s s so s so so s s sw s sw"
speedwalklist.post_wal="n o o o s s s s s o o o o o o o o o o o o o o o o o o o o o o n n n n n w w w w w w w w w w w n"
speedwalklist.min_san="n n n o o o o s o o o o o o o so o o so so o o o so o o o o so s so s so so so so so so o o so o so so so o o so o"
speedwalklist.por_uw="o o o o o o o o o o o o o o so so so so o o o so o o o o no no o"
speedwalklist.por_ril="no n no n n nw nw n nw n n no no n n n w w n n n no"
speedwalklist.mos_ker="w nw nw"
speedwalklist.mine_lor="o so o s s s s s s s s s s sw sw sw sw s s s s s s so sw s o o o o o o o o o o"
speedwalklist.min_us="n n n o n o o no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no nw no n no n"
speedwalklist.min_cor="n n n o o o n no o o o o no n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.min_ash="n n n o o o o s o o o o o o o so o o so so o o o so o o o o so s so s so so so so so so o o so o so so so o o so o s so so o o o so o o o o o o o o o o no o no no no no s"
speedwalklist.min_alo="n n n o o o n no o o o o no so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o no no no no no no n no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.wal_post="s o o o o o o o o o o o s s s s s w w w w w w w w w w w w w w w w w w w w w w n n n n n w w w s"
speedwalklist.wal_haendler="s o o o o o o o o o o o s s s s s s s s s s s s s s s o o o o o o o o o o o o o o o o o o o o"
speedwalklist.affe_gol="s no o so s s s sw w w sw w w w w w w w w w w w w w w"
speedwalklist.min_abt="n n n o o o n no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no n kletter_n kletter_no kletter_no no n kletter_n kletter_n kletter_n n"
speedwalklist.los_ale="o o o o o o o o o o o o s s s so sw so so o o so so so o o so s sw s s s so s s sw s o o"
speedwalklist.los_jer="o o o o o o o o o o o o"
speedwalklist.los_ver="o o o o o o o o o o o o s s s so sw so so o o so so so o o so s sw s s s so s s sw s s sw sw sw sw sw sw sw sw w w w sw"
speedwalklist.wal_schmied="s o o o o o o o o o o o s s s s s w w w w w w w w w w w w w w w w w w w w s s s s s s s s s s"
speedwalklist.haf_jer="w w w w nw n n n"
speedwalklist.haf_amp="w w w w w w w w w w w w w w sw w w sw w w nw no no o o o no o o o o o no no"
speedwalklist.gwen_tin="s w w w w w w w w w w w nw w nw w w w w w nw w w w w nw w w nw w w w w nw"
speedwalklist.haendler_wal="w w w w w w w w w w w w w w w w w w w w n n n n n n n n n n n n n n n w w w w w w w w w w w n"
speedwalklist.lor_mine="w w w w w w w w w w n no nw n n n n n n no no no no n n n n n n n n n n w nw w"
speedwalklist.lim_hol="sw w nw nw w w w w nw no o o no o o no o no no o so o no o o no o o no no n n w w"
speedwalklist.ash_druide="n nw no no no no no no no no"
speedwalklist.druide_ash="sw sw sw sw sw sw sw sw so s"
speedwalklist.min_druide="n n n o o o n no o o o o no so o o o o o o o o o no s s"
speedwalklist.druide_min="n n sw w w w w w w w w w nw sw w w w w sw s w w w s s s"
speedwalklist.cor_druide="s sw so so so so so so"
speedwalklist.druide_cor="nw nw nw nw nw nw no n"
speedwalklist.us_druide="no o o o no no no n n"
speedwalklist.druide_us="s s sw sw sw w w w sw"
speedwalklist.los_druide="o o o o o o o o o"
speedwalklist.druide_los="w w w w w w w w w"
speedwalklist.dol_druide="w w"
speedwalklist.druide_dol="o o"
speedwalklist.dol_haf="s so o o o o o o o o"
speedwalklist.haf_dol="w w w w w w w w nw n"
speedwalklist.gwen_haf="n n n n n o o o o o o o o n n n n"
speedwalklist.haf_gwen="s s s s w w w w w w w w s s s s s"
speedwalklist.tin_siedlung="so o o o o no nw n n w"
speedwalklist.siedlung_tin="o s s so sw w w w w nw"
speedwalklist.tin_jagd="no o o o o n n n n n n h"
speedwalklist.jagd_tin="r s s s s s s w w w w sw"
speedwalklist.tin_mine="n n n n n n n n n n n o o o o o o o o o o o o o o n n n n n n n nw"
speedwalklist.mine_tin="so s s s s s s s w w w w w w w w w w w w w w s s s s s s s s s s s"
speedwalklist.lor_haf="w w w w w w w w w w s s s s s s"
speedwalklist.haf_lor="n n n n n n o o o o o o o o o o"
speedwalklist.lor_druide="w w w w w w w w w w w w"
speedwalklist.druide_lor="o o o o o o o o o o o o"
speedwalklist.camp_tief="so o o o o so s s s so so so so s so s so s so s so so s s so so so s s sw sw s s s sw s so so s so so s so sw so s so s so so so so so so so s s s s so so so so so s s s s s s sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw s s s so s so s s s s s sw sw s s s s s so so so so s s s s so o o o o o so so s sw sw sw s s s s s s s s so so"
speedwalklist.tief_camp="nw nw n n n n n n n n no no no n nw nw w w w w w nw n n n n nw nw nw nw n n n n n no no n n n n n nw n nw n n n no no no no no no no no no no no no no no no no no no no no no n n n n n n nw nw nw nw nw n n n n nw nw nw nw nw nw nw n nw n nw no nw n nw nw n nw nw n no n n n no no n n nw nw nw n n nw nw n nw n nw n nw n nw nw nw nw n n n nw w w w w nw"
speedwalklist.camp_druide="o o o s"
speedwalklist.druide_camp="n w w w"
speedwalklist.alo_tor="w w w w w w sw w w s s s"
speedwalklist.tor_alo="n n n o o no o o o o o o"
speedwalklist.ash_tor="n o o o o no no no no no"
speedwalklist.tor_ash="sw sw sw sw sw w w w w s"
speedwalklist.tor_min="n n nw w w w w w w w nw w w w s s s"
speedwalklist.min_tor="n n n o o o so o o o o o o o so s s"
speedwalklist.tor_cor="nw nw n n n n n no no no o no o no n"
speedwalklist.cor_tor="s sw w sw w sw sw sw s s s s s so so"
speedwalklist.haf_sol="sw sw sw sw n n n n n n"
speedwalklist.sol_haf="s s s s s s no no no no"
speedwalklist.sol_hain="w w w w w s s sw sw sw sw w w w sw w sw w nw w nw n no"
speedwalklist.hain_sol="sw s so o so o no o no o o o no no no no n n o o o o o"
speedwalklist.sol_schmied="s s s s s s no no no no no o o o o o no no no"
speedwalklist.schmied_sol="sw sw sw w w w w w sw sw sw sw sw n n n n n n"
speedwalklist.tor_us="o kletter_o kletter_o kletter_so kletter_s kletter_s so so so so s s s sw sw sw w w w sw"
speedwalklist.us_tor="no o o o no no no n n n nw nw nw nw kletter_n kletter_n kletter_nw kletter_w kletter_w w"
speedwalklist.tol_ilme="o o o o no"
speedwalklist.ilme_tol="sw w w w w"
speedwalklist.tol_schmied="no"
speedwalklist.schmied_tol="sw"
speedwalklist.tol_druide="o o o n n"
speedwalklist.druide_tol="s s w w w"
speedwalklist.tol_haf="o o o no no n nw nw nw w w w w w"
speedwalklist.haf_tol="o o o o o so so so s sw sw w w w"
speedwalklist.tor_abt="n n kletter_n no"
speedwalklist.abt_tor="sw kletter_s s s"
speedwalklist.tor_san="no no no no no no no no n o so o so so so o o o s o"
speedwalklist.san_tor="w n w w w nw nw nw w nw w s sw sw sw sw sw sw sw sw"
speedwalklist.uw_toe="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw so s s s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw no no nw nw nw nw nw nw sw sw s s sw sw so s so s so so so sw s o so o so o no o o o o o o o o so o o o o o no o o o o o so so so so so sw s s sw sw sw sw w w sw w w sw w w w sw w w sw w w w sw w s so so so"
speedwalklist.toe_uw="nw nw nw n o no o o o no o o no o o o no o o no o o no no no no n n no nw nw nw nw nw w w w w w sw w w w w w nw w w w w w w w w sw w nw w nw w n no nw nw nw n nw n nw no no n n no no so so so so so so sw sw no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n n n nw no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.camp_see="so o o o o so s s s so so so so s so s so s so s so so s s so so so s s sw sw s s s sw s so so s so so s so sw so s so s so so so so so so so s s s s so so so so so s s s s s s sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw s s s so s so s s s s s sw sw s s s s s so so so so s s s s so o o o o o so so s sw sw sw s s s s s s s s so so so w s s o s s o s o o s o o so so o so o o o o o o o o"
speedwalklist.see_camp="w w w w w w w w nw w nw nw w w n w w n w n n w n n o nw nw nw n n n n n n n n no no no n nw nw w w w w w nw n n n n nw nw nw nw n n n n n no no n n n n n nw n nw n n n no no no no no no no no no no no no no no no no no no no no no n n n n n n nw nw nw nw nw n n n n nw nw nw nw nw nw nw n nw n nw no nw n nw nw n nw nw n no n n n no no n n nw nw nw n n nw nw n nw n nw n nw n nw nw nw nw n n n nw w w w w nw"
speedwalklist.sol_druide="w w w w w s s sw sw sw sw w w w sw w sw w nw"
speedwalklist.druide_sol="so o no o no o o o no no no no n n o o o o o"
speedwalklist.min_schlucht="n n n o o o so o o o o o o o so o o so so o o o s kletter_s kletter_so kletter_sw kletter_sw s s kletter_s kletter_s"
speedwalklist.schlucht_min="kletter_n kletter_n n n kletter_no kletter_no kletter_nw kletter_n n w w w nw nw w w nw w w w w w w w nw w w w s s s"
speedwalklist.mine_ruw="w w sw nw sw sw s s o o so s so so o o so so o so o so so o so so o o no o o no o o so no no no o o no o no"
speedwalklist.ruw_mine="sw w sw w w sw sw sw nw w w sw w w sw w w nw nw w nw nw w nw w nw nw w w nw nw n nw w w n n no no so no o o"
speedwalklist.sol_barde="w w w w w s s sw sw sw sw w w w sw w sw w nw w nw n no nw no no no"
speedwalklist.barde_sol="sw sw sw so sw s so o so o no o no o o o no no no no n n o o o o o"
speedwalklist.barde_ruw="s sw nw sw sw s s o o so s so so o o so so o so o so so o so so o o no o o no o o so no no no o o no o no"
speedwalklist.ruw_barde="sw w sw w w sw sw sw nw w w sw w w sw w w nw nw w nw nw w nw w nw nw w w nw nw n nw w w n n no no so no n"
speedwalklist.tol_barde="no no no no no no kletter_n kletter_no kletter_n kletter_n kletter_no n"
speedwalklist.barde_tol="s kletter_sw kletter_s kletter_s kletter_sw kletter_s sw sw sw sw sw sw"
speedwalklist.tol_magier2="o o o o no n n n n n kletter_n kletter_n kletter_n kletter_n kletter_no kletter_nw no nw kletter_n kletter_no"
speedwalklist.magier2_tol="kletter_sw kletter_s so sw kletter_so kletter_sw kletter_s kletter_s kletter_s kletter_s s s s s s sw w w w w"
speedwalklist.tol_magier1="o o o o no no n nw nw nw no no no nw nw nw nw sw s so s"
speedwalklist.magier1_tol="n nw n no so so so so sw sw sw so so so s sw sw w w w w"
speedwalklist.san_barde="s so s s s s s s"
speedwalklist.barde_san="n n n n n n nw n"
speedwalklist.ash_barde="n n so so so so so so so so so so so so s"
speedwalklist.barde_ash="n nw nw nw nw nw nw nw nw nw nw nw nw s s"
speedwalklist.alo_barde="w w w w w w sw w w w w n n n n n n n n n n schwimme_n n n n n"
speedwalklist.barde_alo="s s s s schwimme_s s s s s s s s s s s o o o o no o o o o o o"
speedwalklist.min_barde="n n n o o o o s w w w w w w w w w s s o oeffne_tuer o n"
speedwalklist.barde_min="s w w n n o o o o o o o o o n w w w w s s s"
speedwalklist.us_barde="no o o o o o n n n"
speedwalklist.barde_us="s s s w w w w w sw"
speedwalklist.ril_barde="nw n n nw nw oeffne_tuer n hoch w w w sw sw s s s s s so s so"
speedwalklist.barde_ril="nw n nw n n n n n no no o o o runter oeffne_tuer s so so s s so"
speedwalklist.skal_barde="oeffne_tor s s s w w w w w w nw"
speedwalklist.barde_skal="so o o o o o o n n oeffne_tor n"
speedwalklist.los_barde="o o o o o o o"
speedwalklist.barde_los="w w w w w w w"
speedwalklist.lor_barde="nw nw nw nw nw nw nw nw nw n no no no n no no no no no"
speedwalklist.barde_lor="sw sw sw sw sw s sw sw sw s so so so so so so so so so"
speedwalklist.tin_barde="s s s s s s s s s w w w w w w w w w w w w w w w w w"
speedwalklist.barde_tin="o o o o o o o o o o o o o o o o o n n n n n n n n n"
speedwalklist.ker_barde="no o no o so o o n no so so o so o s"
speedwalklist.barde_ker="n w nw w nw nw sw s w w nw w sw w sw"
speedwalklist.hol_barde="w w w w w w w w w w w w w w w w w w w w w w w w w s s s s s w"
speedwalklist.barde_hol="o n n n n n o o o o o o o o o o o o o o o o o o o o o o o o o"
speedwalklist.hol_haf="w w w w w w w w w w w w w w w w w w w w w w w w w s w w w w w s s s s s s s s s s s s s s w sw w w nw w sw s s s sw w w sw s s s"
speedwalklist.haf_hol="n n n no o o no n n n no o so o o no o n n n n n n n n n n n n n n o o o o o n o o o o o o o o o o o o o o o o o o o o o o o o o"
speedwalklist.lim_druide="sw w nw nw w w w w nw w w w w w w w w"
speedwalklist.druide_lim="o o o o o o o o so o o o o so so o no"
speedwalklist.hol_jagd="w w w w w w w w w w w w w w w w w w w w w w w w w s"
speedwalklist.jagd_hol="n o o o o o o o o o o o o o o o o o o o o o o o o o"
speedwalklist.hol_koch="w w w w w w w w w w w w w w w w w w w w w w w w w s w w w w w s s s s s"
speedwalklist.koch_hol="n n n n n o o o o o n o o o o o o o o o o o o o o o o o o o o o o o o o"
speedwalklist.hol_mine="s s s s s s s s s w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w"
speedwalklist.mine_hol="o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o n n n n n n n n n"
speedwalklist.hol_farm="s s s s w w sw w w sw w nw w sw sw w sw w w sw w w sw so o o o o so so o s s s"
speedwalklist.farm_hol="n n n w nw nw w w w w nw no o o no o o no o no no o so o no o o no o o n n n n"
speedwalklist.amp_magier="sw sw w w w w w sw w w w sw sw so o o no o o no o o o o o o o o o o o o o o runter o o o s s o o o o o o o s sw"
speedwalklist.magier_amp="no n w w w w w w w n n w w w hoch w w w w w w w w w w w w w w sw w w sw w w nw no no o o o no o o o o o no no"
speedwalklist.gwen_magier="n n n n n o o o o o o o o s s o o o"
speedwalklist.magier_gwen="w w w n n w w w w w w w w s s s s s"
speedwalklist.ker_magier="no s s s so so so betrete_hoehle no nw sw sw"
speedwalklist.magier_ker="no no so sw raus nw nw nw n n n sw"
speedwalklist.lor_magier="nw nw nw nw nw nw nw nw nw n no no no n n n n n n n n n n n w w w w w w w"
speedwalklist.magier_lor="o o o o o o o s s s s s s s s s s s sw sw sw s so so so so so so so so so"
speedwalklist.jer_magier="n n nw n n"
speedwalklist.magier_jer="s s so s s"
speedwalklist.ker_magier="so so s so so betrete_höhle no nw sw sw"
speedwalklist.magier_ker="no no so sw raus nw nw n nw nw"
speedwalklist.orks_alo="o so s s so so s w s s"
speedwalklist.alo_orks="n n o n nw nw n n nw w"
speedwalklist.gwen_schmied="s w w w w w w w w sw"
speedwalklist.schmied_gwen="no o o o o o o o o n"
speedwalklist.uw_tempel="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o"
speedwalklist.tempel_uw="w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.uw_mine="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so s s s s s s betrete_loch"
speedwalklist.mine_uw="o n n n n n n nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.camp_mine="so o o o o no o o o o no o o no n n n n mine"
speedwalklist.mine_camp="s s s s s sw w w sw w w w w sw w w w w nw"
speedwalklist.us_mine="nw w nw w w nw nw w nw  w w sw s sw sw s s s"
speedwalklist.mine_us="n n n no no n no o o so o so so o o so o so"
speedwalklist.alo_form="s o so o o o o o o o so"
speedwalklist.form_alo="nw w w w w w w w nw w n"
speedwalklist.ash_form="n nw w nw w w nw w nw nw nw nw nw nw"
speedwalklist.form_ash="so so so so so so o so o o so o so s"
speedwalklist.cor_form="so o no"
speedwalklist.form_cor="sw w nw"
speedwalklist.us_form="no o o o o o so o o no nw no no o o o"
speedwalklist.form_us="w w w sw sw so sw w w nw w w w w w sw"
speedwalklist.min_form="n n n o o o n no o o o o no so o o o o o o o o o n nw nw nw nw"
speedwalklist.form_min="so so so so s w w w w w w w w w nw sw w w w w sw s w w w s s s"
speedwalklist.tol_form="o o o o no no n nw nw nw no no no nw nw nw nw sw nw w w w nw sw w"
speedwalklist.form_tol="o no so o o o so no so so so so sw sw sw so so so s sw sw w w w w"
speedwalklist.lim_muehle="sw w nw nw w w w w nw no o o no o o no o no no o so o no o n"
speedwalklist.muehle_lim="s w sw w nw w sw sw w sw w w sw w w sw so o o o o so so o no"
speedwalklist.lim_schmied="sw w nw nw w w w w nw no o o no o o no o no no o so o no o o no o o no o"
speedwalklist.schmied_lim="w sw w w sw w w sw w nw w sw sw w sw w w sw w w sw so o o o o so so o no"
speedwalklist.toe_yol="so so s s s s s sw sw sw sw s s s so so o o o o o o so o o o o so o o no o"
speedwalklist.yol_toe="w sw w w nw w w w w nw w w w w w w nw nw n n n no no no no n n n n n nw nw"
speedwalklist.alo_wahrsager="w w w w w w sw w w w w w w w w w w w w w w sw nw w nw nw nw nw nw nw n n n n nw n nw nw nw"
speedwalklist.wahrsager_alo="so so so s so s s s s so so so so so so o so no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.ash_dichter="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n w w w w"
speedwalklist.dichter_ash="o o o o s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.alo_papierfalter="s o so sw sw s s sw sw sw sw sw sw"
speedwalklist.papierfalter_alo="no no no no no no n n no no nw w n"
speedwalklist.wtoe_htoe="so so so so so so so so so so so s s s s s s s s so s sw s s s s s s s s sw sw sw sw sw sw sw s s s s s s sw sw s w w w w w w"
speedwalklist.htoe_wtoe="o o o o o o n no no n n n n n n no no no no no no no n n n n n n n n no n nw n n n n n n n n nw nw nw nw nw nw nw nw nw nw nw"
speedwalklist.abt_alo="s kletter_s sw sw sw sw sw sw sw so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.alo_abt="w w w w w w sw w w w w w w w w w w w w w w sw nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw no no no no no no no kletter_n n"
speedwalklist.ilme_haf="no n nw nw nw w w w w w w"
speedwalklist.haf_ilme="o o o o o o so so so s sw"
speedwalklist.alo_teich="w w w w w w sw w w w w nw"
speedwalklist.teich_alo="so o o o o no o o o o o o"
speedwalklist.tor_teich="n n n w w w n"
speedwalklist.teich_tor="s o o o s s s"
speedwalklist.gwen_siedlung="s w w w w w w w w w w w nw w nw w w w w w nw w w w w nw w w nw no nw n n w"
speedwalklist.siedlung_gwen="o s s so sw so o o so o o o o so o o o o o so o so o o o o o o o o o o o n"
speedwalklist.dhun_uw="n no n w nw nw w nw nw nw no nw n n nw w sw w"
speedwalklist.uw_dhun="o no o so s s so sw so so so o so so o s sw  s"
speedwalklist.abt_teich="s kletter_sw s sw sw sw sw sw sw so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o o o o o o o o o o o no"
speedwalklist.min_teich="n n n o o o n no o o o o o o o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o no no no no no no n n o o o o o o o o o no"
speedwalklist.teich_abt="sw w w w w w w w w w w w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw no no no no no no n kletter_no n"
speedwalklist.teich_min="sw w w w w w w w w w s s sw sw sw sw sw sw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w w w w w w w sw s w w w s s s"
speedwalklist.teich_us="sw w w w w w w w w w w w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.us_teich="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o o o o o o o o o o o no"
speedwalklist.jas_toe="no no nw nw nw nw nw nw sw sw s s sw sw so s so s so so so sw s o so o so o no o o o o o o o o so o o o o o no o o o o o so so so so so sw s s sw sw sw sw w w sw w w sw w w w sw w w sw w w w sw w s so so so"
speedwalklist.toe_jas="nw nw nw n o no o o o no o o no o o o no o o no o o no no no no n n no nw nw nw nw nw w w w w w sw w w w w w nw w w w w w w w w sw w nw w nw w n no nw nw nw n nw n nw no no n n no no so so so so so so sw sw"
speedwalklist.camp_skal="so o o o o so s s s so so so so s so s so s so s so so s s so so so s s sw sw s s s sw s sw s sw sw sw sw s sw sw s sw sw sw sw sw sw sw sw sw s sw w w w sw so so sw w sw s sw"
speedwalklist.skal_camp="no n no o no nw nw no o o o no n no no no no no no no no no n no no n no no no no n no n no n n n no no n n nw nw nw n n nw nw n nw n nw n nw n nw nw nw nw n n n nw w w w w nw"
speedwalklist.moor_jas="no no no no no n no o so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.jas_moor="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw w sw s sw sw sw sw sw"
speedwalklist.cor_alo="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o no no no no no n no no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.alo_cor="w w w w w w sw w w w w w w w w w w w w w w sw sw s sw sw sw sw sw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.min_imker="n n n o o o n no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n no o sw"
speedwalklist.imker_min="no w sw s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw s w w w s s s"
speedwalklist.lederer_min="o sw s nw nw nw n n w w w w w w w w w w w"
speedwalklist.min_lederer="o o o o o o o o o o o s s so so so n no w"
speedwalklist.dinsel_jas="sw sw sw sw sw sw sw sw w w w nw w w nw w w nw w w w nw w w w nw w nw w nw w nw w nw w w nw w w w w w w w w w s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.jas_dinsel="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n o o o o o o o o o so o o so o so o so o so o so o o o so o o o so o o so o o so o o o no no no no no no no no"
speedwalklist.jas_magier="oeffne_tor s sw w"
speedwalklist.magier_jas="o no oeffne_tor n"
speedwalklist.ril_magier="nw n n nw nw w sw nw"
speedwalklist.magier_ril="so no o so so s s so"
speedwalklist.skal_magier="oeffne_tor s s s w w w w w w n"
speedwalklist.magier_skal="s o o o o o o n n oeffne_tor n"
speedwalklist.aug_ker="o o o o o so o o so o o no o o o n o o o so o o no o o so s s so s sw s w w nw w sw w sw"
speedwalklist.ker_aug="no o no o so o o n no n nw n n nw w w sw w w nw w w w s w w w sw w w nw w w nw w w w w w"
speedwalklist.aug_mos="o o o o o so o o so o o no o o o n o o o so o o no o o so s s so s sw s w w nw w sw w sw so so o"
speedwalklist.mos_aug="w nw nw no o no o so o o n no n nw n n nw w w sw w w nw w w w s w w w sw w w nw w w nw w w w w w"
speedwalklist.us_dhun="no o o o o o so o o no o o o o so o so oeffne_tor s s s s s s sw s s s s s sw s"
speedwalklist.dhun_us="n no n n n n n no n n n n n oeffne_tor n nw w nw w w w w sw w w nw w w w w w sw"
speedwalklist.teich_cor="sw w w w w w w w w sw sw s sw sw sw sw sw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.cor_teich="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o no no no no no n no no o o o o o o o o no"
speedwalklist.cor_apf="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o o"
speedwalklist.apf_cor="w w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.apf_teich="n no no no no n no no o o o o o o o o o n"
speedwalklist.teich_apf="s w w w w w w w w w sw sw s sw sw sw sw s"
speedwalklist.alo_apf="w w w w w w sw w w w w w w w w w w w w w w sw sw s sw sw sw sw sw o"
speedwalklist.apf_alo="w no no no no no n no no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.min_apf="n n n o o o n no o o o o no so o o o o o o o o o no o no no no no no no o o o o o o o o so o o o o o o o o o o o o o"
speedwalklist.apf_min="w w w w w w w w w w w w w nw w w w w w w w w sw sw sw sw sw sw w sw w w w w w w w w w nw sw w w w w sw s w w w s s s"
speedwalklist.apf_ash="w so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.ash_apf="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw o"
speedwalklist.us_apf="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so sw s sw sw sw sw s"
speedwalklist.apf_us="n no no no no n no nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.haendler_us="n o so o o o so o o so o so so o o so o so"
speedwalklist.us_haendler="nw w nw w w nw nw w nw w w nw w w w nw w s"
speedwalklist.min_magier1="o o n oeffne_tuer n"
speedwalklist.magier1_min="oeffne_tuer s s w w"
speedwalklist.min_magier2="n n n o o o s s s s s s s s s s s s"
speedwalklist.magier2_min="n n n n n n n n n n n n w w w s s s"
speedwalklist.min_magier3="o o o o o o o o o o o s s so so so w h w"
speedwalklist.magier3_min="o r o nw nw nw n n w w w w w w w w w w w"
speedwalklist.post_ril="nw no no o so so s s so"
speedwalklist.ril_post="nw n n nw nw w sw sw so"
speedwalklist.jas_schmied="oeffne_tor s sw s s s s s so o s s s oeffne_tuer o"
speedwalklist.schmied_jas="oeffne_tuer w n n n w nw n n n n n no oeffne_tor n"
speedwalklist.jas_post="oeffne_tor s sw s s s s s so o o o o s o"
speedwalklist.post_jas="w n w w w w nw n n n n n no oeffne_tor n"
speedwalklist.skal_schmied="oeffne_tor s s s w w w w w w s s s s s s oeffne_tuer o"
speedwalklist.schmied_skal="oeffne_tuer w n n n n n n o o o o o o n n oeffne_tor n"
speedwalklist.skal_haendler="oeffne_tor s s s o o o s s s s s s s s s w w w oeffne_tuer s"
speedwalklist.haendler_skal="oeffne_tuer n o o o n n n n n n n n n w w w n n oeffne_tor n"
speedwalklist.skal_bank="oeffne_tor s s s s s s w w w w oeffne_tuer n"
speedwalklist.bank_skal="oeffne_tuer s o o o o n n n n n oeffne_tor n"
speedwalklist.skal_post="oeffne_tor s s s s s s w w w s s oeffne_tuer w"
speedwalklist.post_skal="oeffne_tuer o n n o o o n n n n n oeffne_tor n"
speedwalklist.skal_tief="no n no o no nw nw no o o o no n no no no no no no no no no n no no n no no no no n no so so s so so s so sw so s so s so so so so so so so s s s s so so so so so s s s s s s sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw s s s so s so s s s s s sw sw s s s s s so so so so s s s s so o o o o o so so s sw sw sw s s s s s s s s so so"
speedwalklist.tief_skal="nw nw n n n n n n n n no no no n nw nw w w w w w nw n n n n nw nw nw nw n n n n n no no n n n n n nw n nw n n n no no no no no no no no no no no no no no no no no no no no no n n n n n n nw nw nw nw nw n n n n nw nw nw nw nw nw nw n nw n nw no nw n nw nw n nw nw sw s sw sw sw sw s sw sw s sw sw sw sw sw sw sw sw sw s sw w w w sw so so sw w sw s sw"
speedwalklist.min_schmied="o o o o o o o o o o o o o o s s"
speedwalklist.schmied_min="n n w w w w w w w w w w w w w w"
speedwalklist.cor_san="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s sw w w w w sw s so o o o o o o o so o o so so o o o so o o o o so s so s so so so so so so o o so o so so so o o o s o"
speedwalklist.san_cor="w n w w w nw nw nw w nw w w nw nw nw nw nw nw n nw n nw w w w w nw w w w nw nw w w nw w w w w w w w nw n no o o o o no n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.tempel_jas="o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw so s s s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.jas_tempel="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n n n nw no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w"
speedwalklist.ash_teich="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw no no no no no n no no o o o o o o o o o n"
speedwalklist.teich_ash="s w w w w w w w w w sw sw s sw sw sw sw sw so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.camp_kap="nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so no o o o o no o o o o o o so o o o o o no o no no no n n n nw nw w nw w nw w w w nw nw w w w w w w w sw w w nw w sw w w w w w w nw w w w w n n n"
speedwalklist.kap_camp="s s s o o o o so o o o o o o no o so o o no o o o o o o o so so o o o so o so o so so s s s sw sw sw w sw w w w w w nw w w w w w w sw w w w w sw nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so"
speedwalklist.kap_tempel="s s s o o o o so o o o o o o no o so o o no o o o o o o o so so o o o so o so o so so s s s sw sw sw so o so o o o o o so o o o so o o so o o o o o so o o o so o o"
speedwalklist.tempel_kap="w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw no no no n n n nw nw w nw w nw w w w nw nw w w w w w w w sw w w nw w sw w w w w w w nw w w w w n n n"
speedwalklist.tempel_jas="o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw so s s s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.jas_tempel="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n n n nw no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w"
speedwalklist.jas_haendler="oeffne_tor s sw s s sw s s sw oeffne_tor s w"
speedwalklist.haendler_jas="o oeffne_tor n no n n no n n no oeffne_tor n"
speedwalklist.camp_kap="nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so no o o o o no o o o o o o so o o o o o no o no no no n n n nw nw w nw w nw w w w nw nw w w w w w w w sw w w nw w sw w w w w w w nw w w w w n n n"
speedwalklist.kap_camp="s s s o o o o so o o o o o o no o so o o no o o o o o o o so so o o o so o so o so so s s s sw sw sw w sw w w w w w nw w w w w w w sw w w w w sw nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so"
speedwalklist.tempel_camp="w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so"
speedwalklist.camp_tempel="nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o"
speedwalklist.cor_abt="s sw w sw w sw sw sw sw sw sw sw sw w sw w w nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no n kletter_n kletter_no kletter_no no n kletter_n kletter_n kletter_n n"
speedwalklist.abt_cor="s kletter_s kletter_s kletter_s s sw kletter_sw kletter_sw kletter_s s sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w sw sw s s s so s so s s s s s s s sw so so o so so s so so o o no o no no no no no no no no o no o no n"
speedwalklist.abt_apf="s kletter_s kletter_s kletter_s s sw kletter_sw kletter_sw kletter_s s o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so sw s sw sw sw sw s"
speedwalklist.apf_abt="n no no no no n no nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w n kletter_n kletter_no kletter_no no n kletter_n kletter_n kletter_n n"
speedwalklist.ker_haf="no o no o so o o n no n nw n n nw no o o o o o o o o o o o o o o"
speedwalklist.haf_ker="w w w w w w w w w w w w w w sw so s s so s sw s w w nw w sw w sw"
speedwalklist.haf_aug="w w w w w w w w w w w w w w sw w w sw w w nw w w w sw w w sw w w nw w w nw w w w w w"
speedwalklist.aug_haf="o o o o o so o o so o o no o o no o o o so o o no o o no o o o o o o o o o o o o o o"
speedwalklist.aug_bank="oeffne_tor w w w nw nw oeffne_tuer s"
speedwalklist.bank_aug="oeffne_tuer n so so o o oeffne_tor o"
speedwalklist.jer_schmied="s s s so sw so so o o so so so o no schmiede"
speedwalklist.schmied_jer="raus sw w nw nw nw w w nw nw no nw n n n"
speedwalklist.schmied_ale="raus s so s sw s s s so s s sw o so"
speedwalklist.ale_schmied="nw w no n n nw n n n no n nw n schmiede"
speedwalklist.ale_jer="n nw n n nw n n n no n nw w w nw nw nw w w nw nw no nw n n n"
speedwalklist.jer_ale="s s s so sw so so o o so so so o o so s sw s s s so s s so s"
speedwalklist.jer_ver="s s s so sw so so o o so so so o o so s sw s s s so s s sw s s sw sw sw sw sw sw sw sw w w w sw"
speedwalklist.ver_jer="no o o o no no no no no no no no n n no n n nw n n n no n nw w w nw nw nw w w nw nw no nw n n n"
speedwalklist.haf_ale="w w w w sw so so o o so so so o o so s sw s s s so s s so s"
speedwalklist.ale_haf="n nw n n nw n n n no n nw w w nw nw nw w w nw nw no o o o o"
speedwalklist.haf_ver="w w w w sw so so o o so so so o o so s sw s s s so s s sw s s sw sw sw sw sw sw sw sw w w w sw"
speedwalklist.ver_haf="no o o o no no no no no no no no n n no n n nw n n n no n nw w w nw nw nw w w nw nw no o o o o"
speedwalklist.schmied_ver="raus s so s sw s s s so s s sw s s sw sw sw sw sw sw sw sw w w w sw"
speedwalklist.ver_schmied="no o o o no no no no no no no no n n no n n nw n n n no n nw n schmiede"
speedwalklist.jer_bank="n n nw w w w w s"
speedwalklist.bank_jer="n o o o o so s s"
speedwalklist.los_magier="no o o o o o o o o o o o o o o o no n"
speedwalklist.magier_los="s sw w w w w w w w w w w w w w w w sw"
speedwalklist.haendler_jer="w s so s s"
speedwalklist.jer_haendler="n n nw n o"
speedwalklist.lor_haendler="w w w w w w w w w nw n n oeffne_tuer w"
speedwalklist.haendler_lor="oeffne_tuer o s s so o o o o o o o o o"
speedwalklist.lor_bank="w w w w w w w w w nw n n n n w w oeffne_tuer n"
speedwalklist.bank_lor="oeffne_tuer s o o s s s s so o o o o o o o o o"
speedwalklist.schmied_siedlung="no w w w nw w nw w w w w w nw w w w w nw w w nw no nw n n w"
speedwalklist.siedlung_schmied="o s s so sw so o o so o o o o so o o o o o so o so o o o sw"
speedwalklist.tief_see="so w s s o s s o s o o s o o so so o so o o o o o o o o"
speedwalklist.see_tief="w w w w w w w w nw w nw nw w w n w w n w n n w n n o nw"
speedwalklist.us_muel="no o o o o o so o o no nw no no o o no no n n nw nw nw w"
speedwalklist.muel_us="o so so so s s sw sw w w sw sw so sw w w nw w w w w w sw"
speedwalklist.muel_dhun="o so so so s s sw sw w w sw sw so o o o o so o so s s s sw s o s sw s s s s s sw s"
speedwalklist.dhun_muel="n no n n n n n no n w n no n n n nw w nw w w w w nw no no o o no no n n nw nw nw w"
speedwalklist.uw_muel="o no o so s s so sw so so so o so so o n n n n no n no nw n n n nw w nw w w w w nw no no o o no no n n nw nw nw w"
speedwalklist.muel_uw="o so so so s s sw sw w w sw sw so o o o o so o so s s s so sw s sw s s s s w nw nw w nw nw nw no nw n n nw w sw w"
speedwalklist.ilme_bank="hoch hoch s baumhaus"
speedwalklist.bank_ilme="ausgang n runter runter"
speedwalklist.ilme_post="hoch hoch w baumhaus"
speedwalklist.post_ilme="ausgang o runter runter"
speedwalklist.ilme_haendler="hoch w n w baumhaus"
speedwalklist.haendler_ilme="ausgang o s o runter"
speedwalklist.uw_ilme="n kletter_treppe o n w hoch n no o o o so no so so so so sw sw sw so so so s sw"
speedwalklist.ilme_uw="no n nw nw nw no no no nw nw nw nw sw nw w w w sw s kletter_treppe o s w hoch s"
speedwalklist.ilme_magier1="no n nw nw nw no no no nw nw nw nw sw s so s"
speedwalklist.magier1_ilme="n nw n no so so so so sw sw sw so so so s sw"
speedwalklist.ilme_magier2="n n n n n kletter_n kletter_n kletter_n kletter_n kletter_no kletter_nw no nw kletter_n kletter_no"
speedwalklist.magier2_ilme="kletter_sw kletter_s so sw kletter_so kletter_sw kletter_s kletter_s kletter_s kletter_s s s s s s"
speedwalksafety={}
for name,way in pairs(speedwalklist) do
		speedwalksafety[name]=false
end
speedwalksafety['min_dhun']=true
speedwalksafety['dhun_min']=true
speedwalksafety['cor_us']=true
speedwalksafety['kap_uw']=true
speedwalksafety['cor_min']=true
speedwalksafety['camp_uw']=true
speedwalksafety['uw_kap']=true
speedwalksafety['uw_jas']=true
speedwalksafety['jer_haf']=true
speedwalksafety['jas_uw']=true
speedwalksafety['uw_camp']=true
speedwalksafety['us_uw']=true
speedwalksafety['ash_us']=true
speedwalksafety['ash_san']=true
speedwalksafety['ash_min']=true
speedwalksafety['ash_alo']=true
speedwalksafety['us_min']=true
speedwalksafety['us_cor']=true
speedwalksafety['us_ash']=true
speedwalksafety['us_alo']=true
speedwalksafety['alo_us']=true
speedwalksafety['alo_san']=true
speedwalksafety['wl_tin']=true
speedwalksafety['tin_wl']=true
speedwalksafety['tin_gwen']=true
speedwalksafety['skal_uw']=true
speedwalksafety['san_min']=true
speedwalksafety['alo_min']=true
speedwalksafety['alo_ash']=true
speedwalksafety['uw_us']=true
speedwalksafety['uw_skal']=true
speedwalksafety['uw_por']=true
speedwalksafety['san_alo']=true
speedwalksafety['san_ash']=true
speedwalksafety['ril_por']=true
speedwalksafety['min_san']=true
speedwalksafety['por_uw']=true
speedwalksafety['por_ril']=true
speedwalksafety['min_us']=true
speedwalksafety['min_cor']=true
speedwalksafety['min_ash']=true
speedwalksafety['min_alo']=true
speedwalksafety['haf_jer']=true
speedwalksafety['gwen_tin']=true
speedwalksafety['dol_druide']=true
speedwalksafety['druide_dol']=true
speedwalksafety['dol_haf']=true
speedwalksafety['haf_dol']=true
speedwalksafety['gwen_haf']=true
speedwalksafety['haf_gwen']=true
speedwalksafety['tin_siedlung']=true
speedwalksafety['siedlung_tin']=true
speedwalksafety['tin_jagd']=true
speedwalksafety['jagd_tin']=true
speedwalksafety['tin_mine']=true
speedwalksafety['mine_tin']=true
speedwalksafety['camp_tief']=true
speedwalksafety['tief_camp']=true
speedwalksafety['camp_druide']=true
speedwalksafety['druide_camp']=true
speedwalksafety['haf_sol']=true
speedwalksafety['sol_haf']=true
speedwalksafety['sol_schmied']=true
speedwalksafety['schmied_sol']=true
speedwalksafety['tol_ilme']=true
speedwalksafety['ilme_tol']=true
speedwalksafety['tol_schmied']=true
speedwalksafety['schmied_tol']=true
speedwalksafety['tol_druide']=true
speedwalksafety['druide_tol']=true
speedwalksafety['tol_haf']=true
speedwalksafety['haf_tol']=true
speedwalksafety['camp_see']=true
speedwalksafety['see_camp']=true
speedwalksafety['tol_barde']=true
speedwalksafety['barde_tol']=true
speedwalksafety['tol_magier2']=true
speedwalksafety['magier2_tol']=true
speedwalksafety['tol_magier1']=true
speedwalksafety['magier1_tol']=true
speedwalksafety['min_barde']=true
speedwalksafety['barde_min']=true
speedwalksafety['ril_barde']=true
speedwalksafety['barde_ril']=true
speedwalksafety['skal_barde']=true
speedwalksafety['barde_skal']=true
speedwalksafety['tin_barde']=true
speedwalksafety['barde_tin']=true
speedwalksafety['gwen_magier']=true
speedwalksafety['magier_gwen']=true
speedwalksafety['jer_magier']=true
speedwalksafety['magier_jer']=true
speedwalksafety['gwen_schmied']=true
speedwalksafety['schmied_gwen']=true
speedwalksafety['uw_tempel']=true
speedwalksafety['tempel_uw']=true
speedwalksafety['us_mine']=true
speedwalksafety['mine_us']=true
speedwalksafety['ash_form']=true
speedwalksafety['form_ash']=true
speedwalksafety['tol_form']=true
speedwalksafety['form_tol']=true
speedwalksafety['ilme_haf']=true
speedwalksafety['haf_ilme']=true
speedwalksafety['alo_teich']=true
speedwalksafety['teich_alo']=true
speedwalksafety['gwen_siedlung']=true
speedwalksafety['siedlung_gwen']=true
speedwalksafety['dhun_uw']=true
speedwalksafety['uw_dhun']=true
speedwalksafety['min_teich']=true
speedwalksafety['teich_min']=true
speedwalksafety['teich_us']=true
speedwalksafety['us_teich']=true
speedwalksafety['camp_skal']=true
speedwalksafety['skal_camp']=true
speedwalksafety['cor_alo']=true
speedwalksafety['alo_cor']=true
speedwalksafety['lederer_min']=true
speedwalksafety['min_lederer']=true
speedwalksafety['jas_magier']=true
speedwalksafety['magier_jas']=true
speedwalksafety['ril_magier']=true
speedwalksafety['magier_ril']=true
speedwalksafety['skal_magier']=true
speedwalksafety['magier_skal']=true
speedwalksafety['toe_yol']=true
speedwalksafety['yol_toe']=true
speedwalksafety['us_dhun']=true
speedwalksafety['dhun_us']=true
speedwalksafety['teich_cor']=true
speedwalksafety['cor_teich']=true
speedwalksafety['cor_apf']=true
speedwalksafety['apf_cor']=true
speedwalksafety['apf_teich']=true
speedwalksafety['teich_apf']=true
speedwalksafety['alo_apf']=true
speedwalksafety['apf_alo']=true
speedwalksafety['min_apf']=true
speedwalksafety['apf_min']=true
speedwalksafety['apf_ash']=true
speedwalksafety['ash_apf']=true
speedwalksafety['us_apf']=true
speedwalksafety['apf_us']=true
speedwalksafety['haendler_us']=true
speedwalksafety['us_haendler']=true
speedwalksafety['min_magier1']=true
speedwalksafety['magier1_min']=true
speedwalksafety['min_magier2']=true
speedwalksafety['magier2_min']=true
speedwalksafety['min_magier3']=true
speedwalksafety['magier3_min']=true
speedwalksafety['post_ril']=true
speedwalksafety['ril_post']=true
speedwalksafety['jas_schmied']=true
speedwalksafety['schmied_jas']=true
speedwalksafety['jas_post']=true
speedwalksafety['post_jas']=true
speedwalksafety['skal_schmied']=true
speedwalksafety['schmied_skal']=true
speedwalksafety['skal_haendler']=true
speedwalksafety['haendler_skal']=true
speedwalksafety['skal_bank']=true
speedwalksafety['bank_skal']=true
speedwalksafety['skal_post']=true
speedwalksafety['post_skal']=true
speedwalksafety['skal_tief']=true
speedwalksafety['tief_skal']=true
speedwalksafety['min_schmied']=true
speedwalksafety['schmied_min']=true
speedwalksafety['cor_san']=true
speedwalksafety['san_cor']=true
speedwalksafety['tempel_jas']=true
speedwalksafety['jas_tempel']=true
speedwalksafety['ash_teich']=true
speedwalksafety['teich_ash']=true
speedwalksafety['camp_kap']=true
speedwalksafety['kap_camp']=true
speedwalksafety['kap_tempel']=true
speedwalksafety['tempel_kap']=true
speedwalksafety['tempel_jas']=true
speedwalksafety['jas_tempel']=true
speedwalksafety['jas_haendler']=true
speedwalksafety['haendler_jas']=true
speedwalksafety['camp_kap']=true
speedwalksafety['kap_camp']=true
speedwalksafety['tempel_camp']=true
speedwalksafety['camp_tempel']=true
speedwalksafety['aug_bank']=true
speedwalksafety['bank_aug']=true
speedwalksafety['jer_ver']=true
speedwalksafety['ver_jer']=true
speedwalksafety['haf_ver']=true
speedwalksafety['ver_haf']=true
speedwalksafety['jer_bank']=true
speedwalksafety['bank_jer']=true
speedwalksafety['haendler_jer']=true
speedwalksafety['jer_haendler']=true
speedwalksafety['schmied_siedlung']=true
speedwalksafety['siedlung_schmied']=true
speedwalksafety['tief_see']=true
speedwalksafety['see_tief']=true
speedwalksafety['us_muel']=true
speedwalksafety['muel_us']=true
speedwalksafety['muel_dhun']=true
speedwalksafety['dhun_muel']=true
speedwalksafety['uw_muel']=true
speedwalksafety['muel_uw']=true
speedwalksafety['ilme_bank']=true
speedwalksafety['bank_ilme']=true
speedwalksafety['ilme_post']=true
speedwalksafety['post_ilme']=true
speedwalksafety['ilme_haendler']=true
speedwalksafety['haendler_ilme']=true
speedwalksafety['uw_ilme']=true
speedwalksafety['ilme_uw']=true
speedwalksafety['ilme_magier1']=true
speedwalksafety['magier1_ilme']=true
speedwalksafety['ilme_magier2']=true
speedwalksafety['magier2_ilme']=true