speedwalklist = {}
speedwalklist.abt_alo="s kletter_s sw sw sw sw sw sw sw so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.abt_apf="s kletter_s kletter_s kletter_s s sw kletter_sw kletter_sw kletter_s s o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so sw s sw sw sw sw s"
speedwalklist.abt_cor="s kletter_s kletter_s kletter_s s sw kletter_sw kletter_sw kletter_s s sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w sw sw s s s so s so s s s s s s s sw so so o so so s so so o o no o no no no no no no no no o no o no n"
speedwalklist.abt_min="s kletter_s kletter_s kletter_s s sw kletter_sw kletter_sw kletter_s s sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w sw sw s s s so s so s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw s sw w w w w w w"
speedwalklist.abt_teich="s kletter_sw s sw sw sw sw sw sw so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o o o o o o o o o o o no"
speedwalklist.abt_tor="sw kletter_s s s"
speedwalklist.abt_zwerge="s kletter_s kletter_s kletter_s s sw kletter_sw kletter_sw kletter_s s sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.affe_gol="s no o so s s s sw w w sw w w w w w w w w w w w w w w"
speedwalklist.alch_jas="o o s s s sw w w w w w w w nw n n n n n no n"
speedwalklist.ale_haf="n nw n n nw n n n no n nw w w nw nw nw w w nw nw no o o o o"
speedwalklist.ale_jer="n nw n n nw n n n no n nw w w nw nw nw w w nw nw no nw n n n"
speedwalklist.ale_los="w w n no n n nw n n n no n nw w w nw nw nw w w nw nw no nw n n n w w w w w w w w w w w w"
speedwalklist.ale_schmied="nw w no n n nw n n n no n nw n schmiede"
speedwalklist.alo_abt="w w w w w w sw w w w w w w w w w w w w w w sw nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw no no no no no no no kletter_n n"
speedwalklist.alo_apf="w w w w w w sw w w w w w w w w w w w w w w sw sw s sw sw sw sw sw o"
speedwalklist.alo_ash="w w w w w w sw w w w w w w w w w w w w w w sw s sw sw sw sw sw sw so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.alo_barde="w w w w w w sw w w w w n n n n n n n n n n schwimme_n n n n n"
speedwalklist.alo_cor="w w w w w w sw w w w w w w w w w w w w w w sw sw s sw sw sw sw sw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.alo_form="s o so o o o o o o o so"
speedwalklist.alo_min="w w w w w w sw w w w w w w w w w w w w w w sw sw s sw sw sw sw sw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw sw w w w w sw s sw w w w w w w"
speedwalklist.alo_orks="n n o n nw nw n n nw w"
speedwalklist.alo_papierfalter="s o so sw sw s s sw sw sw sw sw sw"
speedwalklist.alo_san="w w w w w w sw w w w w w w w w w w w w w w sw s sw sw sw sw sw sw so so s s so s s s s s s s so so s s s so so so so so o so o o so o so sw sw sw sw w sw w w w w w w w w w w nw w w w nw nw n"
speedwalklist.alo_teich="w w w w w w sw w w w w nw"
speedwalklist.alo_tor="w w w w w w sw w w s s s"
speedwalklist.alo_wahrsager="w w w w w w sw w w w w w w w w w w w w w w sw nw w nw nw nw nw nw nw n n n n nw n nw nw nw"
speedwalklist.alo_wlm="w w s s s s s s s betrete"
speedwalklist.alo_zwerge="w w w w w w sw w w w w w w w w w w w w w w sw nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.aloz_baecker="n n n n w"
speedwalklist.aloz_bank="n n n n n n n o o o o o s s s s o o o"
speedwalklist.aloz_gast="n n n n n o"
speedwalklist.aloz_haendler="o so so so o o n n n n no o o no n n w"
speedwalklist.aloz_haf="o so so so o o o o o o o o so o o o o n n nw nw nw"
speedwalklist.aloz_leder="o so so so o o o o o n"
speedwalklist.aloz_zlm1="s s sw o"
speedwalklist.aloz_zlm2="n n n n n n n o o o o o o o o o n hoch aufwaerts oben hoch hochsteigen oben aufwaerts oben"
speedwalklist.aloz_post="n n n n n n o n o o o o o o s"
speedwalklist.aloz_werkzeug="o so so so o o n o"
speedwalklist.amp_aug="sw sw w w w w w sw w w w sw sw w w w s w w w sw w w nw w w nw w w w w w"
speedwalklist.amp_haf="sw sw w w w w w sw w w w sw sw so o o no o o no o o o o o o o o o o o o o o"
speedwalklist.amp_ker="sw sw w w w w w sw w w w sw sw so o o no o o so s s so s sw s w w nw w sw w sw"
speedwalklist.amp_umi="sw sw w w w w w sw w w w sw sw so o o no o o no o o o o o o o o o o o o o o runter o o o o"
speedwalklist.amp_wl="sw sw w w w w w sw w w w sw sw w w w s w n n n n"
speedwalklist.anl_camp="sw w w w w w w w sw w w w sw w w w w nw w sw w w sw w w w w sw w w w w nw"
speedwalklist.anl_jas="so so so so so so sw sw"
speedwalklist.anl_run="s s s s sw"
speedwalklist.anl_skal="nw nw nw nw w nw n nw nw n nw nw sw s sw sw sw sw s sw sw s sw sw sw sw sw sw sw sw sw s sw w w w sw so so sw w sw s sw"
speedwalklist.anl_tempel="so so so o o o no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w"
speedwalklist.anl_tief="w w sw w w w w w nw nw w w sw sw w w w w w w w w w sw w w sw"
speedwalklist.anl_toe="s so so so"
speedwalklist.apf_abt="n no no no no n no nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w n kletter_n kletter_no kletter_no no n kletter_n kletter_n kletter_n n"
speedwalklist.apf_alo="w no no no no no n no no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.apf_ash="w so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.apf_cor="w w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.apf_min="w w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw sw w w w w sw s sw w w w w w w"
speedwalklist.apf_teich="n no no no no n no no o o o o o o o o o n"
speedwalklist.apf_zwerge="n no no no no n no nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.arg_ruw="no n no o so o so so o so o no o o o no o so o no o o no o so so so so so s s sw sw so so sw so s s"
speedwalklist.ash_alo="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw no no no no no no n no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.ash_apf="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw o"
speedwalklist.ash_barde="n n so so so so so so so so so so so so s"
speedwalklist.ash_dichter="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n w w w w"
speedwalklist.ash_druide="n nw no no no no no no no no"
speedwalklist.ash_form="n nw w nw w w nw w nw nw nw nw nw nw"
speedwalklist.ash_min="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw sw w w w w sw s sw w w w w w w"
speedwalklist.ash_san="n sw sw sw sw w sw w w w w w w w w w w nw w w w nw nw n"
speedwalklist.ash_teich="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw no no no no no n no no o o o o o o o o o n"
speedwalklist.ash_tor="n o o o o no no no no no"
speedwalklist.ash_wlm="no o o o o o o o o o betrete_zelt"
speedwalklist.ash_zwerge="n nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw no no no no no no n nw w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.ashz_bank="no so"
speedwalklist.ashz_gast="w w s s so sw"
speedwalklist.ashz_haendler="w w s"
speedwalklist.ashz_lotterie="so so so so so no no"
speedwalklist.ashz_zlm="w w w w n"
speedwalklist.ashz_makler="w w w n n o"
speedwalklist.ashz_post="n n w w s"
speedwalklist.ashz_therme="w w w w w s s"
speedwalklist.ashz_wlm="n n n n sw"
speedwalklist.aug_amp="o o o o o so o o so o o no o o o n o o o no no o o o no o o o o o no no"
speedwalklist.aug_bank="oeffne_tor w w w nw nw oeffne_tuer s"
speedwalklist.aug_haf="o o o o o so o o so o o no o o no o o o so o o no o o no o o o o o o o o o o o o o o"
speedwalklist.aug_ker="o o o o o so o o so o o no o o o n o o o so o o no o o so s s so s sw s w w nw w sw w sw"
speedwalklist.aug_mos="o o o o o so o o so o o no o o o n o o o so o o no o o so s s so s sw s w w nw w sw w sw so so o"
speedwalklist.aug_troph="w w w nw n n n n o o o betrete_huette runter"
speedwalklist.baecker_aloz="o s s s s"
speedwalklist.bank_aloz="w w w n n n n w w w w w s s s s s s s"
speedwalklist.bank_ashz="nw sw"
speedwalklist.bank_aug="oeffne_tuer n so so o o oeffne_tor o"
speedwalklist.bank_corz="w n"
speedwalklist.bank_dhun2="s s so o o o so so"
speedwalklist.bank_haendler="nw sw w w s"
speedwalklist.bank_ilme="ausgang n runter runter"
speedwalklist.bank_jas="w n n oeffne_tor no no n n n n no oeffne_tor n"
speedwalklist.bank_jer="n o o o o so s s"
speedwalklist.bank_lor="oeffne_tuer s o o s s s s so o o o o o o o o o"
speedwalklist.bank_min="n o"
speedwalklist.bank_skal="oeffne_tuer s o o o o n n n n n oeffne_tor n"
speedwalklist.bank_umi="n w n n n n o"
speedwalklist.bank_us="s o so o o o so"
speedwalklist.bank_wal="s s w w w w w w w w w w w w w w s s s s s o o o o o o o o o o o s"
speedwalklist.bank_yol="o s s w w w w w"
speedwalklist.barde_alo="s s s s schwimme_s s s s s s s s s s s o o o o no o o o o o o"
speedwalklist.barde_ash="n nw nw nw nw nw nw nw nw nw nw nw nw s s"
speedwalklist.barde_hol="o n n n n n o o o o o o o o o o o o o o o o o o o o o o o o o"
speedwalklist.barde_ker="n w nw w nw nw sw s w w nw w sw w sw"
speedwalklist.barde_lor="sw sw sw sw sw s sw sw sw s so so so so so so so so so"
speedwalklist.barde_mio="s w w n n o o o o o o o o o nw sw o o o o o"
speedwalklist.barde_ril="nw n nw n n n n n no no o o o runter oeffne_tuer s so so s s so"
speedwalklist.barde_ruw="s sw nw sw sw s s o o so s so so o o so so o so o so so o so so o o no o o no o o so no no no o o no o no"
speedwalklist.barde_san="n n n n n n nw n"
speedwalklist.barde_skal="so o o o o o o n n oeffne_tor n"
speedwalklist.barde_sol="sw sw sw so sw s so o so o no o no o o o no no no no n n o o o o o"
speedwalklist.barde_tin="o o o o o o o o o o o o o o o o o n n n n n n n n n"
speedwalklist.barde_tol="s kletter_sw kletter_s kletter_s kletter_sw kletter_s sw sw sw sw sw sw"
speedwalklist.barde_zwerge="s s s w w w w w sw"
speedwalklist.bote_mio="oeffne_tuer w sw w nw sw w w sw sw sw s s"
speedwalklist.bruecke_muw="o o no o no no o o o"
speedwalklist.bruecke_muw2="nw nw nw w w w nw w w w sw w w nw w w w w w n"
speedwalklist.camp_anl="so o o o o no o o o o no o o no o so o o o o no o o o no o o o o o o o no"
speedwalklist.camp_dk="sw sw sw sw sw sw sw s s s s s s sw s sw sw sw w w sw sw sw s s s s s"
speedwalklist.camp_druide="o o o s"
speedwalklist.camp_kap="nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so no o o o o no o o o o o o so o o o o o no o no no no n n n nw nw w nw w nw w w w nw nw w w w w w w w sw w w nw w sw w w w w w w nw w w w w n n n"
speedwalklist.camp_mine="so o o o o no o o o o no o o no n n n n mine"
speedwalklist.camp_see="so o o o o so s s s so so so so s so s so s so s so so s s so so so s s sw sw s s s sw s so so s so so s so sw so s so s so so so so so so so s s s s so so so so so s s s s s s sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw s s s so s so s s s s s sw sw s s s s s so so so so s s s s so o o o o o so so s sw sw sw s s s s s s s s so so so w s s o s s o s o o s o o so so o so o o o o o o o o"
speedwalklist.camp_skal="so o o o o so s s s so so so so s so s so s so s so so s s so so so s s sw sw s s s sw s sw s sw sw sw sw s sw sw s sw sw sw sw sw sw sw sw sw s sw w w w sw so so sw w sw s sw"
speedwalklist.camp_stangenschloss="nw nw nw nw nw nw n n no n n n nw o o o o o o o o o o o o o o o o betrete_loch"
speedwalklist.camp_tempel="nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o"
speedwalklist.camp_tief="so o o o o so s s s so so so so s so s so s so s so so s s so so so s s sw sw s s s sw s so so s so so s so sw so s so s so so so so so so so s s s s so so so so so s s s s s s sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw s s s so s so s s s s s sw sw s s s s s so so so so s s s s so o o o o o so so s sw sw sw s s s s s s s s so so"
speedwalklist.camp_ts="so o o o o no o o o o no o o no o so o o o o no o o o no o o n"
speedwalklist.camp_uw="nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so s so so so so so so so o o o so o o o o no no o"
speedwalklist.cor_abt="s sw w sw w sw sw sw sw sw sw sw sw w sw w w nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no n kletter_n kletter_no kletter_no no n kletter_n kletter_n kletter_n n"
speedwalklist.cor_alo="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o no no no no no n no no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.cor_apf="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o o"
speedwalklist.cor_druide="s sw so so so so so so"
speedwalklist.cor_form="so o no"
speedwalklist.cor_min="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s sw w w w w sw s sw w w w w w w"
speedwalklist.cor_san="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s sw w w w w sw s so o o o o o o o so o o so so o o o so o o o o so s so s so so so so so so o o so o so so so o o o s o"
speedwalklist.cor_teich="s sw w sw w sw sw sw sw sw sw sw sw w sw w w sw s s s s s s sw s sw s s s so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o no no no no no n no no o o o o o o o o no"
speedwalklist.cor_tor="s sw w sw w sw sw sw s s s s s so so"
speedwalklist.cor_zwerge="s sw w sw w sw sw sw sw sw sw sw sw w sw w w nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no nw no n no n"
speedwalklist.corz_bank="s o"
speedwalklist.corz_haendler="n w"
speedwalklist.corz_haf="w w w w"
speedwalklist.corz_zlm="w w w s"
speedwalklist.corz_post="o o n"
speedwalklist.corz_wlm="w w s"
speedwalklist.dhun_haf="n no n w nw nw w nw nw nw no nw w"
speedwalklist.dhun_min="n no n n n n n no n n n n n oeffne_tor n nw w nw w w w w sw w w nw w w w w w sw s sw s sw so sw sw s s s so s so s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw s sw w w w w w w"
speedwalklist.dhun_nuel="n no n n n n n no n w n no n n n nw w nw w w w w nw no no o o no no n n nw nw nw w"
speedwalklist.dhun_uw="n no n w nw nw w nw nw nw no nw n n nw w sw w"
speedwalklist.dhun_wlm1="n no n n n n n no n w sw h n w"
speedwalklist.dhun_wlm2="n no o o o so s"
speedwalklist.dhun_zwerge="n no n n n n n no n n n n n oeffne_tor n nw w nw w w w w sw w w nw w w w w w sw"
speedwalklist.dhun0_haendler="o o o s so"
speedwalklist.dhun0_schmied="o o no o"
speedwalklist.dhun2_bank="nw nw w w w nw n n"
speedwalklist.dhun2_haendler="w w w w w"
speedwalklist.dhun2_gast="o o so o o so o o"
speedwalklist.dhun2_post="no n n"
speedwalklist.dhun3_zlm="o o o o no n"
speedwalklist.dhun3_wlm1="o o o o o s so"
speedwalklist.dhun3_wlm2="w sw w nw"
speedwalklist.dichter_ash="o o o o s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.dinsel_hoehle="o o o o o o n n n n n o o n"
speedwalklist.dinsel_jas="sw sw sw sw sw sw sw sw w w w nw w w nw w w nw w w w nw w w w nw w nw w nw w nw w nw w w nw w w w w w w w w w s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.dk_camp="n n n n n no no no o o no no no n no n n n n n n no no no no no no no"
speedwalklist.dk_uw="n n n n n no no no o o no no no n no n n n n n n no no no no no no no nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so s so so so so so so so o o o so o o o o no no o"
speedwalklist.dol_druide="w w"
speedwalklist.dol_haf="s so o o o o o o o o"
speedwalklist.druide_ash="sw sw sw sw sw sw sw sw so s"
speedwalklist.druide_camp="n w w w"
speedwalklist.druide_cor="nw nw nw nw nw nw no n"
speedwalklist.druide_dol="o o"
speedwalklist.druide_lim="o o o o o o o o so o o o o so so o no"
speedwalklist.druide_lor="o o o o o o o o o o o o"
speedwalklist.druide_los="w w w w w w w w w"
speedwalklist.druide_min="n n sw w w w w w w w w w nw sw w w w w sw s sw w w w w w w"
speedwalklist.druide_sol="so o no o no o o o no no no no n n o o o o o"
speedwalklist.druide_tol="s s w w w"
speedwalklist.druide_zwerge="s s sw sw sw w w w sw"
speedwalklist.dturm_yol="no no no o o o o o o so o o o o so o o no o"
speedwalklist.dun_haf="schwimme_s schwimme_s schwimme_s schwimme_so schwimme_so schwimme_o schwimme_o schwimme_o schwimme_o schwimme_o schwimme_o schwimme_so schwimme_so so w"
speedwalklist.farm_hol="n n n w nw nw w w w w nw no o o no o o no o no no o so o no o o no o o n n n n"
speedwalklist.form_alo="nw w w w w w w w nw w n"
speedwalklist.form_ash="so so so so so so o so o o so o so s"
speedwalklist.form_cor="sw w nw"
speedwalklist.form_min="so so so so s w w w w w w w w w nw sw w w w w sw s sw w w w w w w"
speedwalklist.form_sol="o o o no no n n o o o o o"
speedwalklist.form_tol="o no so o o o so no so so so so sw sw sw so so so s sw sw w w w w"
speedwalklist.form_zwerge="w w w sw sw so sw w w nw w w w w w sw"
speedwalklist.gast_min="s o o o o no o o"
speedwalklist.gast_ashz="no nw n n o o"
speedwalklist.gast_dhun2="w w nw w w nw w w"
speedwalklist.gast_haf="raus s sw w sw w w nw w w s s s s sw w w sw s s s"
speedwalklist.gast1_aloz="w s s s s s"
speedwalklist.gol_affe="o o o o o o o o o o o o o o no o o no n n n nw w sw n"
speedwalklist.gol_mio="w n n n n n sw o o o o o"
speedwalklist.gol_mine="nw w sw so so o so so o so o o so so o o o o so o so o o o o o o no nw"
speedwalklist.gwen_haendler="n n n n n o o o o o o o o o o o"
speedwalklist.gwen_haf="n n n n n o o o o o o o o n n n n"
speedwalklist.gwen_jagd="s w w w w w w w w w w w w w w w w w w w nw nw nw nw nw nw nw nw nw n n n n hoch"
speedwalklist.gwen_zlm="n n n n n o o o o o o o o s s o o o"
speedwalklist.gwen_schmied="s w w w w w w w w sw"
speedwalklist.gwen_siedlung="s w w w w w w w w w w w nw w nw w w w w w nw w w w w nw w w nw no nw n n w"
speedwalklist.gwen_tin="s w w w w w w w w w w w nw w nw w w w w w nw w w w w nw w w nw w w w w nw"
speedwalklist.haendler_aloz="o s s sw w w sw s s s s w w nw nw nw w"
speedwalklist.haendler_ashz="n o o"
speedwalklist.haendler_corz="o s"
speedwalklist.haendler_dhun0="nw n w w w"
speedwalklist.haendler_dhun2="o o o o o"
speedwalklist.haendler_gwen="w w w w w w w w w w w s s s s s"
speedwalklist.haendler_ilme="ausgang o s o runter"
speedwalklist.haendler_jas="o oeffne_tor n no n n no n n no oeffne_tor n"
speedwalklist.haendler_jer="w s so s s"
speedwalklist.haendler_lor="oeffne_tuer o s s so o o o o o o o o o"
speedwalklist.haendler_min="s w"
speedwalklist.haendler_mio="no o n n n n n sw o o o o o"
speedwalklist.haendler_bank="n o o no so"
speedwalklist.haendler_skal="oeffne_tuer n o o o n n n n n n n n n w w w n n oeffne_tor n"
speedwalklist.haendler_umi="n w w w w w w w n n w n nw"
speedwalklist.haendler_us="n o so o o o so"
speedwalklist.haendler_wal="w w w w w w w w w w w w w w w w w w w w n n n n n n n n n n n n n n n w w w w w w w w w w w n"
speedwalklist.haf_ale="w w w w sw so so o o so so so o o so s sw s s s so s s so s"
speedwalklist.haf_aloz="so so so s s w w w w nw w w w w w w w w nw nw nw w"
speedwalklist.haf_amp="w w w w w w w w w w w w w w sw w w sw w w nw no no o o o no o o o o o no no"
speedwalklist.haf_aug="w w w w w w w w w w w w w w sw w w sw w w nw w w w sw w w sw w w nw w w nw w w w w w"
speedwalklist.haf_corz="o o o o"
speedwalklist.haf_dhun="o so sw so so so o so so o s sw s"
speedwalklist.haf_dol="w w w w w w w w nw n"
speedwalklist.haf_dun="o nw schwimme_nw schwimme_nw schwimme_w schwimme_w schwimme_w schwimme_w schwimme_w schwimme_w schwimme_nw schwimme_nw schwimme_n schwimme_n schwimme_n"
speedwalklist.haf_gast="n n n no o o no n n n n o o so o o no o no n betrete_haus"
speedwalklist.haf_gwen="s s s s w w w w w w w w s s s s s"
speedwalklist.haf_hol="n n n no o o no n n n no o so o o no o n n n n n n n n n n n n n n o o o o o n o o o o o o o o o o o o o o o o o o o o o o o o o"
speedwalklist.haf_ilme="o o o o o o so so so s sw"
speedwalklist.haf_jas="n oeffne_gatter w w nw nw oeffne_tor n"
speedwalklist.haf_jer="w w w w nw n n n"
speedwalklist.haf_ker="w w w w w w w w w w w w w w sw so s s so s sw s w w nw w sw w sw"
speedwalklist.haf_koch="n n n no o o no n n n no o so o o no o n n n n n n n n n"
speedwalklist.haf_lim="n n n no o o no n n n no o so o o no o no o so o o no o o no no o no o o o o so so o no"
speedwalklist.haf_lor="n n n n n n o o o o o o o o o o"
speedwalklist.haf_min="w n n o o o no o o"
speedwalklist.haf_sol="sw sw sw sw n n n n n n"
speedwalklist.haf_tol="o o o o o so so so s sw sw w w w"
speedwalklist.haf_umi="runter o o o o"
speedwalklist.haf_ver="w w w w sw so so o o so so so o o so s sw s s s so s s sw s s sw sw sw sw sw sw sw sw w w w sw"
speedwalklist.haf_vul="n n n n n n nw n no o no o o o o no o no no nw nw n nw nw nw w w w w sw"
speedwalklist.haf2_umi="n n o o n n n n n o"
speedwalklist.hain_sol="sw s so o so o no o no o o o no no no no n n o o o o o"
speedwalklist.her_hol="so o o no o o no o no no o so o no o o no o o no no n n w w"
speedwalklist.her_lim="so sw so o o o o so so o no"
speedwalklist.hoehle_dinsel="s w w s s s s s w w w w w w"
speedwalklist.hol_barde="w w w w w w w w w w w w w w w w w w w w w w w w w s s s s s w"
speedwalklist.hol_farm="s s s s w w sw w w sw w nw w sw sw w sw w w sw w w sw so o o o o so so o s s s"
speedwalklist.hol_haf="w w w w w w w w w w w w w w w w w w w w w w w w w s w w w w w s s s s s s s s s s s s s s w sw w w nw w sw s s s sw w w sw s s s"
speedwalklist.hol_her="o o s s sw sw w w sw w w sw w nw w sw sw w sw w w sw w w nw"
speedwalklist.hol_jagd="w w w w w w w w w w w w w w w w w w w w w w w w w s"
speedwalklist.hol_koch="w w w w w w w w w w w w w w w w w w w w w w w w w s w w w w w s s s s s"
speedwalklist.hol_lim="o o s s sw sw w w sw w w sw w nw w sw sw w sw w w sw w w sw so o o o o so so o no"
speedwalklist.hol_mine="s s s s s s s s s w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w w"
speedwalklist.htoe_wtoe="o o o o o o n no no n n n n n n no no no no no no no n n n n n n n n no n nw n n n n n n n n nw nw nw nw nw nw nw nw nw nw nw"
speedwalklist.ilme_bank="hoch hoch s baumhaus"
speedwalklist.ilme_haendler="hoch w n w baumhaus"
speedwalklist.ilme_haf="no n nw nw nw w w w w w w"
speedwalklist.ilme_zlm1="no n nw nw nw no no no nw nw nw nw sw s so s"
speedwalklist.ilme_zlm2="n n n n n kletter_n kletter_n kletter_n kletter_n kletter_no kletter_nw no nw kletter_n kletter_no"
speedwalklist.ilme_post="hoch hoch w baumhaus"
speedwalklist.ilme_tol="sw w w w w"
speedwalklist.ilme_uw="no n nw nw nw no no no nw nw nw nw sw nw w w w sw s kletter_treppe o s w hoch s"
speedwalklist.ilme_wlm1="no n nw nw nw no no no o so so no"
speedwalklist.ilme_wlm2="h h h w w"
speedwalklist.imker_min="no w sw s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw s sw w w w w w w"
speedwalklist.jagd_gwen="runter s s s s so so so so so so so so so o o o o o o o o o o o o o o o o o o o n"
speedwalklist.jagd_hol="n o o o o o o o o o o o o o o o o o o o o o o o o o"
speedwalklist.jagd_tin="r s s s s s s w w w w sw"
speedwalklist.jas_alch="oeffne_tor s sw s s s s s so o o o o o o o no n n n w w"
speedwalklist.jas_anl="no no nw nw nw nw nw nw"
speedwalklist.jas_bank="oeffne_tor s sw s s s s sw sw oeffne_tor s s o"
speedwalklist.jas_dinsel="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n o o o o o o o o o so o o so o so o so o so o so o o o so o o o so o o so o o so o o o no no no no no no no no"
speedwalklist.jas_haendler="oeffne_tor s sw s s sw s s sw oeffne_tor s w"
speedwalklist.jas_haf="oeffne_tor s so so o o oeffne_gatter s"
speedwalklist.jas_zlm="oeffne_tor s sw w"
speedwalklist.jas_moor="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw w sw s sw sw sw sw sw"
speedwalklist.jas_nekro="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw no"
speedwalklist.jas_post="oeffne_tor s sw s s s s s so o o o o s o"
speedwalklist.jas_schmied="oeffne_tor s sw s s s s s so o s s s oeffne_tuer o"
speedwalklist.jas_tempel="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n n n nw no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w"
speedwalklist.jas_toe="no no nw nw nw nw nw nw sw sw s s sw sw so s so s so so so sw s o so o so o no o o o o o o o o so o o o o o no o o o o o so so so so so sw s s sw sw sw sw w w sw w w sw w w w sw w w sw w w w sw w s so so so"
speedwalklist.jas_uw="no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n n n nw no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.jer_ale="s s s so sw so so o o so so so o o so s sw s s s so s s so s"
speedwalklist.jer_bank="n n nw w w w w s"
speedwalklist.jer_haendler="n n nw n o"
speedwalklist.jer_haf="s s s so o o o o"
speedwalklist.jer_los="w w w w w w w w w w w w"
speedwalklist.jer_zlm="n n nw n n"
speedwalklist.jer_schmied="s s s so sw so so o o so so so o no schmiede"
speedwalklist.jer_ver="s s s so sw so so o o so so so o o so s sw s s s so s s sw s s sw sw sw sw sw sw sw sw w w w sw"
speedwalklist.kap_camp="s s s o o o o so o o o o o o no o so o o no o o o o o o o so so o o o so o so o so so s s s sw sw sw w sw w w w w w nw w w w w w w sw w w w w sw nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so"
speedwalklist.kap_ril="o no no o no no o o no no o so so s s so"
speedwalklist.kap_tempel="s s s o o o o so o o o o o o no o so o o no o o o o o o o so so o o o so o so o so so s s s sw sw sw so o so o o o o o so o o o so o o so o o o o o so o o o so o o"
speedwalklist.kap_uw="s s s o o o o so o o o o o o no o so o o no o o o o o o o so so o o o so o so o so so s s s sw sw sw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.ker_amp="no o no o so o o n no n nw n n nw w w sw w w nw no no o o o no o o o o o no no"
speedwalklist.ker_aug="no o no o so o o n no n nw n n nw w w sw w w nw w w w s w w w sw w w nw w w nw w w w w w"
speedwalklist.ker_barde="no o no o so o o n no so so o so o s"
speedwalklist.ker_haf="no o no o so o o n no n nw n n nw no o o o o o o o o o o o o o o"
speedwalklist.ker_zlm="so so s so so betrete_höhle no nw sw sw"
speedwalklist.ker_mos="so so o"
speedwalklist.ker_run="no o s s s s s s s s w w w w w"
speedwalklist.ker_troph="sw w w nw nw nw"
speedwalklist.ker_wlm="sw w w nw sw s s s"
speedwalklist.koch_haf="s s s s s s s s s w sw w w nw w sw s s s sw w w sw s s s"
speedwalklist.koch_hol="n n n n n o o o o o n o o o o o o o o o o o o o o o o o o o o o o o o o"
speedwalklist.leder_aloz="s w w w w w nw nw nw w"
speedwalklist.lederer_mio="o sw s nw nw nw n n"
speedwalklist.lim_druide="sw w nw nw w w w w nw w w w w w w w w"
speedwalklist.lim_haf="sw w nw nw w w w w sw w sw sw w w sw w w nw w sw w sw w w nw w sw s s s sw w w sw s s s"
speedwalklist.lim_her="sw w nw nw w w w w nw no nw"
speedwalklist.lim_hol="sw w nw nw w w w w nw no o o no o o no o no no o so o no o o no o o no no n n w w"
speedwalklist.lim_muehle="sw w nw nw w w w w nw no o o no o o no o no no o so o no o n"
speedwalklist.lim_schmied="sw w nw nw w w w w nw no o o no o o no o no no o so o no o o no o o no o"
speedwalklist.lor_bank="w w w w w w w w w nw n n n n w w oeffne_tuer n"
speedwalklist.lor_barde="nw nw nw nw nw nw nw nw nw n no no no n no no no no no"
speedwalklist.lor_druide="w w w w w w w w w w w w"
speedwalklist.lor_haendler="w w w w w w w w w nw n n oeffne_tuer w"
speedwalklist.lor_haf="w w w w w w w w w w s s s s s s"
speedwalklist.lor_zlm="nw nw nw nw nw nw nw nw nw n no no no n n n n n n n n n n n w w w w w w w"
speedwalklist.lor_mine="w w w w w w w w w w n no nw n n n n n n no no no no n n n n n n n n n n w nw w"
speedwalklist.los_ale="o o o o o o o o o o o o s s s so sw so so o o so so so o o so s sw s s s so s s sw s o o"
speedwalklist.los_druide="o o o o o o o o o"
speedwalklist.los_jer="o o o o o o o o o o o o"
speedwalklist.los_zlm="no o o o o o o o o o o o o o o o no n"
speedwalklist.los_ver="o o o o o o o o o o o o s s s so sw so so o o so so so o o so s sw s s s so s s sw s s sw sw sw sw sw sw sw sw w w w sw"
speedwalklist.lotterie_ashz="sw sw nw nw nw nw nw"
speedwalklist.zlm1_aloz="w no n n"
speedwalklist.zlm_ashz="s o o o o"
speedwalklist.zlm_corz="n o o o"
speedwalklist.zlm_dhun3="s sw w w w w"
speedwalklist.zlm_gwen="w w w n n w w w w w w w w s s s s s"
speedwalklist.zlm_jas="o no oeffne_tor n"
speedwalklist.zlm_jer="s s so s s"
speedwalklist.zlm_ker="no no so sw raus nw nw n nw nw"
speedwalklist.zlm_lor="o o o o o o o s s s s s s s s s s s sw sw sw s so so so so so so so so so"
speedwalklist.zlm_los="s sw w w w w w w w w w w w w w w w sw"
speedwalklist.zlm_ril="so no o so so s s so"
speedwalklist.zlm_skal="s o o o o o o n n oeffne_tor n"
speedwalklist.zlm_umi="s s w w w w n n w n n w"
speedwalklist.zlm1_ilme="n nw n no so so so so sw sw sw so so so s sw"
speedwalklist.zlm_min="oeffne_tuer s s w w"
speedwalklist.zlm1_tol="n nw n no so so so so sw sw sw so so so s sw sw w w w w"
speedwalklist.zlm2_aloz="runter unten herunter runter abwaerts unten runter abwaerts s w w w w w w w w w s s s s s s s"
speedwalklist.zlm2_ilme="kletter_sw kletter_s so sw kletter_so kletter_sw kletter_s kletter_s kletter_s kletter_s s s s s s"
speedwalklist.zlm1_mio="n n n w nw sw w w sw sw sw s s"
speedwalklist.zlm2_tol="kletter_sw kletter_s so sw kletter_so kletter_sw kletter_s kletter_s kletter_s kletter_s s s s s s sw w w w w"
speedwalklist.zlm2_mio="o r o nw nw nw n n"
speedwalklist.makler_ashz="w s s o o o"
speedwalklist.min_abt="o o o o o o no n no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no n kletter_n kletter_no kletter_no no n kletter_n kletter_n kletter_n n"
speedwalklist.min_alo="o o o o o o no n no o o o o no so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o no no no no no n no no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.min_apf="o o o o o o no n no o o o o no so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o o"
speedwalklist.min_ash="o o o o o o no n no o o o o no so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.min_bank="w s"
speedwalklist.min_cor="o o o o o o no n no o o o o no n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.min_dhun="o o o o o o no n no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no nw no n no n no o o o o o so o o no o o o o so o so oeffne_tor s s s s s s sw s s s s s sw s"
speedwalklist.min_druide="o o o o o o no n no o o o o no so o o o o o o o o o no s s"
speedwalklist.min_form="o o o o o o no n no o o o o no so o o o o o o o o o n nw nw nw nw"
speedwalklist.min_gast="w w sw w w w w n"
speedwalklist.min_haendler="o n"
speedwalklist.min_haf="w w sw w w w s s o"
speedwalklist.min_imker="o o o o o o no n no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n no o sw"
speedwalklist.min_zlm="o o n oeffne_tuer n"
speedwalklist.min_mio="o o o o o o o o o o o"
speedwalklist.min_post="s o"
speedwalklist.min_quelle="o o o o o o no so o o o o o o o so o o so so o"
speedwalklist.min_san="o o o o o o no so o o o o o o o so o o so so o o o so o o o o so s so s so so so so so so o o so o so so so o o so o"
speedwalklist.min_schlucht="o o o o o o no so o o o o o o o so o o so so o o o s kletter_s kletter_so kletter_sw kletter_sw s s kletter_s kletter_s"
speedwalklist.min_schmied="o o o o o o o o o o o o o o s s"
speedwalklist.min_teich="o o o o o o no n no o o o o no so o o o o o o o o o no o no no no no no o no o o o o o o o so o o o o o o o o o o o o no no no no no n no no o o o o o o o o o n"
speedwalklist.min_tor="o o o o o o no so o o o o o o o so s s"
speedwalklist.min_uw="o o o o o o no n no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no nw no n no n no o o o o o so o o no o o o o so o so oeffne_tor s s s s s s sw s s s s w nw nw w nw nw nw no nw n n nw w sw w"
speedwalklist.min_wlm="w w sw w w w w w sw"
speedwalklist.min_zwerge="o o o o o o no n no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no nw no n no n"
speedwalklist.mio_barde="w w w w w no so w w w w w w w w w s s o oeffne_tuer o n"
speedwalklist.mio_bote="n n no no no o o no so o no oeffne_tuer o"
speedwalklist.mio_gol="w w w w w no s s s s s o"
speedwalklist.mio_haendler="w w w w w no s s s s s w sw"
speedwalklist.mio_lederer="s s so so so n no w"
speedwalklist.mio_min="w w w w w w w w w w w"
speedwalklist.mio_stadtwache="o o o o o o s s s s so s w w n n"
speedwalklist.mio_wlm1="w w w w w no so w w w w w w w w w s s s s w n ziehe_kordel"
speedwalklist.mio_wlm2="o o o o o o s s s s so s w w n"
speedwalklist.mio_zlm1="n n no no no o o no so o s s s"
speedwalklist.mio_zlm2="s s so so so w h w"
speedwalklist.mine_camp="s s s s s sw w w sw w w w w sw w w w w nw"
speedwalklist.mine_gol="so sw w w w w w w nw w nw w w w w nw nw w w nw w nw nw w nw nw no o so"
speedwalklist.mine_hol="o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o o n n n n n n n n n"
speedwalklist.mine_lor="o so o s s s s s s s s s s sw sw sw sw s s s s s s so sw s o o o o o o o o o o"
speedwalklist.mine_por="o o o o o so o o s sw s sw"
speedwalklist.mine_ruw="w w sw nw sw sw s s o o so s so so o o so so o so o so so o so so o o no o o no o o so no no no o o no o no"
speedwalklist.mine_tin="so s s s s s s s w w w w w w w w w w w w w w s s s s s s s s s s s"
speedwalklist.mine_us="n n n no no n no"
speedwalklist.mine_uw="o n n n n n n nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.moor_jas="no no no no no n no o so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.moor_nekro="no no no no no no no n n"
speedwalklist.mos_aug="w nw nw no o no o so o o n no n nw n n nw w w sw w w nw w w w s w w w sw w w nw w w nw w w w w w"
speedwalklist.mos_ker="w nw nw"
speedwalklist.muehle_lim="s w sw w nw w sw sw w sw w w sw w w sw so o o o o so so o no"
speedwalklist.muw_bruecke="w w w sw sw w sw w w"
speedwalklist.muw_muw2="w sw w w w w w w nw w w w w w w w w w w w w w nw w nw w w w"
speedwalklist.muw_spalt="w w w w w nw n o o"
speedwalklist.muw2_bruecke="s o o o o o so o o no o o o so o o o so so so"
speedwalklist.muw2_muw="o o o so o so o o o o o o o o o o o o o so o o o o o o no o"
speedwalklist.nekro_jas="sw so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.nekro_moor="s s sw sw sw sw sw sw sw"
speedwalklist.nekro_uw="sw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n n n nw no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.nuel_dhun="o so so so s s sw sw w w sw sw so o o o o so o so s s s sw s o s sw s s s s s sw s"
speedwalklist.nuel_uw="o so so so s s sw sw w w sw sw so o o o o so o so oeffne_tor s s s s s s sw s s s s w nw nw w nw nw nw no nw n n nw w sw w"
speedwalklist.nuel_zwerge="o so so so s s sw sw w w sw sw so sw w w nw w w w w w sw"
speedwalklist.orks_alo="o so s s so so s w s s"
speedwalklist.papierfalter_alo="no no no no no no n n no no nw w n"
speedwalklist.por_mine="no n no n w w nw w w w w w"
speedwalklist.por_ril="no n no n n nw nw n nw n n no no n n n w w n n n no"
speedwalklist.por_uw="o o o o o o o o o o o o o o so so so so o o o so o o o o no no o"
speedwalklist.post_aloz="n w w w w w w s w s s s s s s"
speedwalklist.post_ashz="n o o s s"
speedwalklist.post_corz="s w w"
speedwalklist.post_dhun2="s s sw"
speedwalklist.post_ilme="ausgang o runter runter"
speedwalklist.post_jas="w n w w w w nw n n n n n no oeffne_tor n"
speedwalklist.post_min="w n"
speedwalklist.post_ril="nw no no o so so s s so"
speedwalklist.post_skal="oeffne_tuer o n n o o o n n n n n oeffne_tor n"
speedwalklist.post_wal="n o o o s s s s s o o o o o o o o o o o o o o o o o o o o o o n n n n n w w w w w w w w w w w n"
speedwalklist.quelle_min="w nw nw w w nw w w w w w w w nw sw w w w w w w"
speedwalklist.quelle_san="o o so o o o o so s so s so so so so so so o o so o so so so o o o s o"
speedwalklist.ril_barde="nw n n nw nw oeffne_tuer n hoch w w w sw sw s s s s s so s so"
speedwalklist.ril_kap="nw n n sw sw sw sw nw nw no n w w sw sw sw w sw sw sw w nw w sw sw sw nw sw sw w"
speedwalklist.ril_zlm="nw n n nw nw w sw nw"
speedwalklist.ril_por="sw s s s o o s s s sw sw s s so s so so s s sw s sw"
speedwalklist.ril_post="nw n n nw nw w sw sw so"
speedwalklist.ril_wlm="nw n n nw nw oeffne_tor n h o o so so s so"
speedwalklist.run_anl="no n n n n"
speedwalklist.run_ker="o o o o o n n n n n n n n w sw"
speedwalklist.ruw_arg="n n nw no nw nw no no n n nw nw nw nw nw w sw w w sw w nw w sw w w w sw w nw w nw nw w nw w sw s sw"
speedwalklist.ruw_barde="sw w sw w w sw sw sw nw w w sw w w sw w w nw nw w nw nw w nw w nw nw w w nw nw n nw w w n n no no so no n"
speedwalklist.ruw_mine="sw w sw w w sw sw sw nw w w sw w w sw w w nw nw w nw nw w nw w nw nw w w nw nw n nw w w n n no no so no o o"
speedwalklist.ruw_scheidung="n n no nw nw nw no no n n nw nw nw nw nw w w sw w sw w nw n betrete_hoehle o o"
speedwalklist.san_alo="s so so o o o so o o o o o o o o o o no o no no no no nw w nw w w nw w nw nw nw nw nw n n n nw nw n n n n n n n nw n n nw nw no no no no no no n no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.san_ash="s so so o o o so o o o o o o o o o o no o no no no no s"
speedwalklist.san_barde="s so s s s s s s"
speedwalklist.san_cor="w n w w w nw nw nw w nw w w nw nw nw nw nw nw n nw n nw w w w w nw w w w nw nw w w nw w w w w w w w nw n no o o o o no n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.san_min="w nw w w nw nw nw w nw w w nw nw nw nw nw nw n nw n nw w w w w nw w w w nw nw w w nw w w w w w w w nw sw w w w w w w"
speedwalklist.san_quelle="w n w w w nw nw nw w nw w w nw nw nw nw nw nw n nw n nw w w w w nw w w"
speedwalklist.san_tor="w n w w w nw nw nw w nw w s sw sw sw sw sw sw sw sw"
speedwalklist.san_zwerge="w n w w w nw nw nw w nw w w nw nw nw nw nw nw n nw n nw w w w w nw w w w nw nw w w nw w w w w w w w nw n no o o o o no n n n no n no n n n n n n no nw nw n nw nw w nw nw no n n n n n n n nw n nw n n n no no nw no n no n"
speedwalklist.scheidung_ruw="betrete_hoehle w sw s so o no o no o o so so so so so s s sw sw so so so sw s s"
speedwalklist.schlucht_min="kletter_n kletter_n n n kletter_no kletter_no kletter_nw kletter_n n w w w nw nw w w nw w w w w w w w nw sw w w w w w w"
speedwalklist.schmied_ale="raus s so s sw s s s so s s sw o so"
speedwalklist.schmied_dhun0="w sw w w"
speedwalklist.schmied_gwen="no o o o o o o o o n"
speedwalklist.schmied_jas="oeffne_tuer w n n n w nw n n n n n no oeffne_tor n"
speedwalklist.schmied_jer="raus sw w nw nw nw w w nw nw no nw n n n"
speedwalklist.schmied_lim="w sw w w sw w w sw w nw w sw sw w sw w w sw w w sw so o o o o so so o no"
speedwalklist.schmied_min="n n w w w w w w w w w w w w w w"
speedwalklist.schmied_siedlung="no w w w nw w nw w w w w w nw w w w w nw w w nw no nw n n w"
speedwalklist.schmied_skal="oeffne_tuer w n n n n n n o o o o o o n n oeffne_tor n"
speedwalklist.schmied_sol="sw sw sw w w w w w sw sw sw sw sw n n n n n n"
speedwalklist.schmied_tol="sw"
speedwalklist.schmied_ver="raus s so s sw s s s so s s sw s s sw sw sw sw sw sw sw sw w w w sw"
speedwalklist.schmied_wal="n n n n n n n n n n o o o o o o o o o o o o o o o o o o o o n n n n n w w w w w w w w w w w n"
speedwalklist.schmied_yol="n n w w w w w"
speedwalklist.see_camp="w w w w w w w w nw w nw nw w w n w w n w n n w n n o nw nw nw n n n n n n n n no no no n nw nw w w w w w nw n n n n nw nw nw nw n n n n n no no n n n n n nw n nw n n n no no no no no no no no no no no no no no no no no no no no no n n n n n n nw nw nw nw nw n n n n nw nw nw nw nw nw nw n nw n nw no nw n nw nw n nw nw n no n n n no no n n nw nw nw n n nw nw n nw n nw n nw n nw nw nw nw n n n nw w w w w nw"
speedwalklist.see_tief="w w w w w w w w nw w nw nw w w n w w n w n n w n n o nw"
speedwalklist.siedlung_gwen="o s s so sw so o o so o o o o so o o o o o so o so o o o o o o o o o o o n"
speedwalklist.siedlung_schmied="o s s so sw so o o so o o o o so o o o o o so o so o o o sw"
speedwalklist.siedlung_tin="o s s so sw w w w w nw"
speedwalklist.skal_anl="no n no o no nw nw no o o o no n no no no no no no no no no n no no n no no no no n no so so s so so s so o so so so so"
speedwalklist.skal_bank="oeffne_tor s s s s s s w w w w oeffne_tuer n"
speedwalklist.skal_barde="oeffne_tor s s s w w w w w w nw"
speedwalklist.skal_camp="no n no o no nw nw no o o o no n no no no no no no no no no n no no n no no no no n no n no n n n no no n n nw nw nw n n nw nw n nw n nw n nw n nw nw nw nw n n n nw w w w w nw"
speedwalklist.skal_haendler="oeffne_tor s s s o o o s s s s s s s s s w w w oeffne_tuer s"
speedwalklist.skal_zlm="oeffne_tor s s s w w w w w w n"
speedwalklist.skal_post="oeffne_tor s s s s s s w w w s s oeffne_tuer w"
speedwalklist.skal_schmied="oeffne_tor s s s w w w w w w s s s s s s oeffne_tuer o"
speedwalklist.skal_tief="no n no o no nw nw no o o o no n no no no no no no no no no n no no n no no no no n no so so s so so s so sw so s so s so so so so so so so s s s s so so so so so s s s s s s sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw sw s s s so s so s s s s s sw sw s s s s s so so so so s s s s so o o o o o so so s sw sw sw s s s s s s s s so so"
speedwalklist.skal_troph="oeffne_tor s s s s s s w w w oeffne_tuer n"
speedwalklist.skal_uw="no n no o no nw nw no o o o no n no no no no no no no no no n no no n no no no no n no n no n n n no no n n nw nw nw n n nw nw n nw n nw n nw n nw nw nw nw n n n nw w w w w nw nw nw nw nw nw nw n n no n n n nw n n n n nw n n nw no no o no o no o o o o o o o o o o o o o o o o o o so o o so s so so so so so so so o o o so o o o o no no o"
speedwalklist.skal_wlm1="oeffne_tor s s s s s s w w w s s s s s s w w w n n oeffne_tuer w"
speedwalklist.skal_wlm2="oeffne_tor s s s w oeffne_suedliche_tuer s"
speedwalklist.slm_us="o s s so"
speedwalklist.sol_barde="w w w w w s s sw sw sw sw w w w sw w sw w nw w nw n no nw no no no"
speedwalklist.sol_druide="w w w w w s s sw sw sw sw w w w sw w sw w nw"
speedwalklist.sol_form="w w w w w s s sw sw w w w"
speedwalklist.sol_haf="s s s s s s no no no no"
speedwalklist.sol_hain="w w w w w s s sw sw sw sw w w w sw w sw w nw w nw n no"
speedwalklist.sol_schmied="s s s s s s no no no no no o o o o o no no no"
speedwalklist.spalt_muw="w w s so o o o o o"
speedwalklist.stadtwache_mio="s s o o n nw n n n n w w w w w w"
speedwalklist.stangenschloss_camp="hoch w w w w w w w w w w w w w w w w so s s s sw s s so so so so so so"
speedwalklist.teich_abt="sw w w w w w w w w w w w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw no no no no no no n kletter_no n"
speedwalklist.teich_alo="so o o o o no o o o o o o"
speedwalklist.teich_apf="s w w w w w w w w w sw sw s sw sw sw sw s"
speedwalklist.teich_ash="s w w w w w w w w w sw sw s sw sw sw sw sw so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.teich_cor="sw w w w w w w w w sw sw s sw sw sw sw sw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw n n n no n no n n n n n n no o o no o no no no no no no no no o no o no n"
speedwalklist.teich_min="s w w w w w w w w w sw sw s sw sw sw sw sw w w w w w w w w w w w w nw w w w w w w w sw w sw sw sw sw sw w sw w w w w w w w w w nw sw w w w w sw s sw w w w w w w"
speedwalklist.teich_tor="s o o o s s s"
speedwalklist.teich_uw="sw w w w w w w w w w w w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n no o o o o o so o o no o o o o so o so oeffne_tor s s s s s s sw s s s s w nw nw w nw nw nw no nw n n nw w sw w"
speedwalklist.teich_wunsch="nw nw nw nw nw nw nw w w w w w n o o o o o"
speedwalklist.teich_zwerge="sw w w w w w w w w w w w nw nw nw nw nw nw n n n n nw n n n no n n n n nw nw w nw w w nw nw w sw nw w nw w sw w sw w w nw w nw w w w sw w w w sw w w w nw w w nw w w w nw no n no n"
speedwalklist.tempel_anl="o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw w w w nw nw nw"
speedwalklist.tempel_camp="w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so"
speedwalklist.tempel_jas="o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw so s s s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.tempel_kap="w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw no no no n n n nw nw w nw w nw w w w nw nw w w w w w w w sw w w nw w sw w w w w w w nw w w w w n n n"
speedwalklist.tempel_uw="w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.therme_ashz="n n o o o o o"
speedwalklist.tief_anl="no o o no o o o o o o o o o no no o o so so o o o o o no o o"
speedwalklist.tief_camp="nw nw n n n n n n n n no no no n nw nw w w w w w nw n n n n nw nw nw nw n n n n n no no n n n n n nw n nw n n n no no no no no no no no no no no no no no no no no no no no no n n n n n n nw nw nw nw nw n n n n nw nw nw nw nw nw nw n nw n nw no nw n nw nw n nw nw n no n n n no no n n nw nw nw n n nw nw n nw n nw n nw n nw nw nw nw n n n nw w w w w nw"
speedwalklist.tief_see="so w s s o s s o s o o s o o so so o so o o o o o o o o"
speedwalklist.tief_skal="nw nw n n n n n n n n no no no n nw nw w w w w w nw n n n n nw nw nw nw n n n n n no no n n n n n nw n nw n n n no no no no no no no no no no no no no no no no no no no no no n n n n n n nw nw nw nw nw n n n n nw nw nw nw nw nw nw n nw n nw no nw n nw nw n nw nw sw s sw sw sw sw s sw sw s sw sw sw sw sw sw sw sw sw s sw w w w sw so so sw w sw s sw"
speedwalklist.tin_barde="s s s s s s s s s w w w w w w w w w w w w w w w w w"
speedwalklist.tin_gwen="so o o o o so o o so o o o o so o o o o o so o so o o o o o o o o o o o n"
speedwalklist.tin_jagd="no o o o o n n n n n n h"
speedwalklist.tin_mine="n n n n n n n n n n n o o o o o o o o o o o o o o n n n n n n n nw"
speedwalklist.tin_siedlung="so o o o o no nw n n w"
speedwalklist.tin_wl="n n n n n n n n n n n n n n n n n w"
speedwalklist.toe_anl="nw nw nw n"
speedwalklist.toe_jas="nw nw nw n o no o o o no o o no o o o no o o no o o no no no no n n no nw nw nw nw nw w w w w w sw w w w w w nw w w w w w w w w sw w nw w nw w n no nw nw nw n nw n nw no no n n no no so so so so so so sw sw"
speedwalklist.toe_uw="nw nw nw n o no o o o no o o no o o o no o o no o o no no no no n n no nw nw nw nw nw w w w w w sw w w w w w nw w w w w w w w w sw w nw w nw w n no nw nw nw n nw n nw no no n n no no so so so so so so sw sw no no o no no o no no no n no no no no no no n n n no no no n n nw nw nw nw nw nw nw n n n no no n nw nw nw w nw w w nw nw nw nw w w w w w nw nw nw nw nw nw nw nw nw nw nw nw nw n n n n nw no n n n no no o o o no no no no n n n no no o o o o o o no o o o no no no no no no no no no n n n no no nw w nw w w nw w w w nw w w w nw w w w w w nw w w nw w w w nw w w w w w nw w nw w sw w w w w w nw w w w w w w sw w w w w sw s so so so so so so so o o o so o o o o no no o"
speedwalklist.toe_yol="so so s s s s s sw sw sw sw s s s so so o o o o o o so o o o o so o o no o"
speedwalklist.tol_barde="no no no no no no kletter_n kletter_no kletter_n kletter_n kletter_no n"
speedwalklist.tol_druide="o o o n n"
speedwalklist.tol_form="o o o o no no n nw nw nw no no no nw nw nw nw sw nw w w w nw sw w"
speedwalklist.tol_haf="o o o no no n nw nw nw w w w w w"
speedwalklist.tol_ilme="o o o o no"
speedwalklist.tol_zlm1="o o o o no no n nw nw nw no no no nw nw nw nw sw s so s"
speedwalklist.tol_zlm2="o o o o no n n n n n kletter_n kletter_n kletter_n kletter_n kletter_no kletter_nw no nw kletter_n kletter_no"
speedwalklist.tol_schmied="no"
speedwalklist.tor_abt="n n kletter_n no"
speedwalklist.tor_alo="n n n o o no o o o o o o"
speedwalklist.tor_ash="sw sw sw sw sw w w w w s"
speedwalklist.tor_cor="nw nw n n n n n no no no o no o no n"
speedwalklist.tor_min="n n nw w w w w w w w nw sw w w w w w w"
speedwalklist.tor_san="no no no no no no no no n o so o so so so o o o s o"
speedwalklist.tor_teich="n n n w w w n"
speedwalklist.tor_zwerge="o kletter_o kletter_o kletter_so kletter_s kletter_s so so so so s s s sw sw sw w w w sw"
speedwalklist.troph_aug="hoch raus w w w s s s s so o o o"
speedwalklist.troph_ker="so so so o o no"
speedwalklist.troph_skal="oeffne_tuer s o o o n n n n n oeffne_tor n"
speedwalklist.troph_us="oeffne_tuer o no o no n n no"
speedwalklist.ts_camp="s w w sw w w w sw w w w w nw w sw w w sw w w w w sw w w w w nw"
speedwalklist.umi_amp="w w w w hoch w w w w w w w w w w w w w w sw w w sw w w nw no no o o o no o o o o o no no"
speedwalklist.umi_bank="w s s s s o s"
speedwalklist.umi_haendler="so s o s s o o o o o o o s"
speedwalklist.umi_haf="w w w w hoch"
speedwalklist.umi_haf2="w s s s s s w w s s"
speedwalklist.umi_zlm="o s s o s s o o o o n n"
speedwalklist.umi_wlm="o o o n o s o n n o o o o o o"
speedwalklist.us_bank="nw w w w nw w n"
speedwalklist.us_haendler="nw w w w nw w s"
speedwalklist.us_mine="sw s sw sw s s s"
speedwalklist.us_slm="nw n n w"
speedwalklist.us_troph="sw s s sw w sw oeffne_tuer w"
speedwalklist.us_zwerge="o o so o so so o o so o so"
speedwalklist.uw_camp="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so"
speedwalklist.uw_dhun="o no o so s s so sw so so so o so so o s sw  s"
speedwalklist.uw_dk="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so sw sw sw sw sw sw sw s s s s s s sw s sw sw sw w w sw sw sw s s s s s"
speedwalklist.uw_ilme="n kletter_treppe o n w hoch n no o o o so no so so so so sw sw sw so so so s sw"
speedwalklist.uw_jas="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw so s s s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw"
speedwalklist.uw_kap="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o no no no n n n nw nw w nw w nw w w w nw nw w w w w w w w sw w w nw w sw w w w w w w nw w w w w n n n"
speedwalklist.uw_min="o no o so s s so sw so so so o so so o n n n n no n n n n n oeffne_tor n nw w nw w w w w sw w w nw w w w w w sw s sw s sw so sw sw s s s so s so s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw s sw w w w w w w"
speedwalklist.uw_mine="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so s s s s s s loch"
speedwalklist.uw_nekro="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw so s s s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so no"
speedwalklist.uw_nuel="o no o so s s so sw so so so o so so o n n n n no n n n n n oeffne_tor n nw w nw w w w w nw no no o o no no n n nw nw nw w"
speedwalklist.uw_por="w sw sw w w w w nw w w w nw nw nw nw w w w w w w w w w w w w w w"
speedwalklist.uw_skal="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n nw w w nw w w w w w w w w w w w w w w w w w w sw w sw w sw sw so s s so s s s s so s s s sw s s so so so so so so so o o o o so s s s so so so so s so s so s so s so so s s so so so s s sw sw s s s sw s sw s sw sw sw sw s sw sw s sw sw sw sw sw sw sw sw sw s sw w w w sw so so sw w sw s sw"
speedwalklist.uw_teich="o no o so s s so sw so so so o so so o n n n n no n n n n n oeffne_tor n nw w nw w w w w sw w w nw w w w w w sw s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o o o o o o o o o o o no"
speedwalklist.uw_tempel="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o"
speedwalklist.uw_toe="w sw sw w w w w nw w w w nw nw nw nw nw nw nw n no o o o o no o o o o o o so o o o o o no o so o so o o o o o so o o o so o o so o o o o o so o o o so o o o so o o so o so sw sw s s s sw sw sw sw sw sw sw sw sw w w w sw w w w w w w sw sw s s s sw sw sw sw w w w sw sw s s s sw so s s s s so so so so so so so so so so so so so o o o o o so so so so o o so o so so so s sw sw s s s so so so so so so so s s sw sw sw s s s sw sw sw sw sw sw s sw sw sw w sw sw w sw sw no no nw nw nw nw nw nw sw sw s s sw sw so s so s so so so sw s o so o so o no o o o o o o o o so o o o o o no o o o o o so so so so so sw s s sw sw sw sw w w sw w w sw w w w sw w w sw w w w sw w s so so so"
speedwalklist.uw_wal="n n n n"
speedwalklist.uw_zwerge="o no o so s s so sw so so so o so so o n n n n no n n n n n oeffne_tor n nw w nw w w w w sw w w nw w w w w w sw"
speedwalklist.ver_haf="no o o o no no no no no no no no n n no n n nw n n n no n nw w w nw nw nw w w nw nw no o o o o"
speedwalklist.ver_jer="no o o o no no no no no no no no n n no n n nw n n n no n nw w w nw nw nw w w nw nw no nw n n n"
speedwalklist.ver_los="no o o o no no no no no no no no n n no n n nw n n n no n nw w w nw nw nw w w nw nw no nw n n n w w w w w w w w w w w w"
speedwalklist.ver_schmied="no o o o no no no no no no no no n n no n n nw n n n no n nw n schmiede"
speedwalklist.vul_haf="no o o o o so so so s so so sw sw w sw w w w w sw w sw s so s s s s s s"
speedwalklist.wahrsager_alo="so so so s so s s s s so so so so so so o so no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.wal_bank="n w w w w w w w w w w w n n n n n o o o o o o o o o o o o o o n n"
speedwalklist.wal_haendler="s o o o o o o o o o o o s s s s s s s s s s s s s s s o o o o o o o o o o o o o o o o o o o o"
speedwalklist.wal_post="s o o o o o o o o o o o s s s s s w w w w w w w w w w w w w w w w w w w w w w n n n n n w w w s"
speedwalklist.wal_schmied="s o o o o o o o o o o o s s s s s w w w w w w w w w w w w w w w w w w w w s s s s s s s s s s"
speedwalklist.wal_uw="s s s s"
speedwalklist.werkzeug_aloz="w s w w nw nw nw w"
speedwalklist.wl_amp="s s s s o n o o o no no o o o no o o o o o no no"
speedwalklist.wl_tin="o s s s s s s s s s s s s s s s s s"
speedwalklist.wlm_alo="raus n n n n n n n o o"
speedwalklist.wlm_ash="ausgang w w w w w w w w w sw"
speedwalklist.wlm_ashz="no s s s s"
speedwalklist.wlm_corz="n o o"
speedwalklist.wlm_ker="n n n no so o o no"
speedwalklist.wlm_ril="nw n nw nw w w r oeffne_tor s so so s s so"
speedwalklist.wlm1_skal="oeffne_tuer o s s o o o n n n n n n o o o n n n n n oeffne_tor n"
speedwalklist.wlm2_skal="oeffne_noerdliche_tuer n o n n n"
speedwalklist.wlm_umi="w w w w w w s s w n w s w w w"
speedwalklist.wlm1_dhun="o s r no o s sw s s s s s sw s"
speedwalklist.wlm1_ilme="sw nw nw w sw sw sw so so so s sw"
speedwalklist.wlm_min="no o o o o o no o o"
speedwalklist.wlm1_dhun3="nw n w w w w w"
speedwalklist.wlm2_dhun="n nw w w w sw s"
speedwalklist.wlm2_dhun3="so o no o"
speedwalklist.wlm2_ilme="o o r r r"
speedwalklist.wlm1_mio="raus s o n n n n o o o o o o o o o nw sw o o o o o"
speedwalklist.wlm2_mio="s o o n nw n n n n w w w w w w"
speedwalklist.wtoe_htoe="so so so so so so so so so so so s s s s s s s s so s sw s s s s s s s s sw sw sw sw sw sw sw s s s s s s sw sw s w w w w w w"
speedwalklist.wunsch_teich="w w w w w s o o o o o so so so so so so so"
speedwalklist.yol_bank="o o o o o n n w"
speedwalklist.yol_dturm="w sw w w nw w w w w nw w w w w w w sw sw sw"
speedwalklist.yol_schmied="o o o o o s s"
speedwalklist.yol_toe="w sw w w nw w w w w nw w w w w w w nw nw n n n no no no no n n n n n nw nw"
speedwalklist.zwerge_abt="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no n kletter_n kletter_no kletter_no no n kletter_n kletter_n kletter_n n"
speedwalklist.zwerge_alo="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so no o o o o o o o o o o o o o o no o o o o o o"
speedwalklist.zwerge_apf="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so sw s sw sw sw sw s"
speedwalklist.zwerge_ash="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o so s sw sw sw sw sw sw so so s s so s s s s s s s so so s s s so so so so so o so o o so o so s"
speedwalklist.zwerge_barde="no o o o o o n n n"
speedwalklist.zwerge_cor="s sw s sw so sw sw s s s so s so s s s s s s s sw so so o so so s so so o o no o no no no no no no no no o no o no n"
speedwalklist.zwerge_dhun="no o o o o o so o o no o o o o so o so oeffne_tor s s s s s s sw s s s s s sw s"
speedwalklist.zwerge_druide="no o o o no no no n n"
speedwalklist.zwerge_form="no o o o o o so o o no nw no no o o o"
speedwalklist.zwerge_min="s sw s sw so sw sw s s s so s so s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw s sw w w w w w w"
speedwalklist.zwerge_nuel="no o o o o o so o o no nw no no o o no no n n nw nw nw w"
speedwalklist.zwerge_san="s sw s sw so sw sw s s s so s so s s s s s s s sw so so o so so s so so sw s s s s s s sw s sw s s s sw w w w w sw s so o o o o o o o so o o so so o o o so o o o o so s so s so so so so so so o o so o so so so o o o s o"
speedwalklist.zwerge_teich="s sw s sw so o o o so o o so o o o no o o o no o o o so o so o o no o no o so o so no o so so o o so o so so s s s s sw s s s so s s s s so so so so so so o o o o o o o o o o o no"
speedwalklist.zwerge_tor="no o o o no no no n n n nw nw nw nw kletter_n kletter_n kletter_nw kletter_w kletter_w w"
speedwalklist.zwerge_us="nw w nw w w nw nw w nw w w"
speedwalklist.zwerge_uw="no o o o o o so o o no o o o o so o so oeffne_tor s s s s s s sw s s s s w nw nw w nw nw nw no nw n n nw w sw w"

speedwalksafety = {}
for name,way in pairs(speedwalklist) do
		speedwalksafety[name] = false
end

speedwalksafety['alch_jas']=true
speedwalksafety['alo_apf']=true
speedwalksafety['alo_ash']=true
speedwalksafety['alo_cor']=true
speedwalksafety['alo_min']=true
speedwalksafety['alo_san']=true
speedwalksafety['alo_teich']=true
speedwalksafety['alo_zwerge']=true
speedwalksafety['aloz_baecker']=true
speedwalksafety['aloz_bank']=true
speedwalksafety['aloz_gast']=true
speedwalksafety['aloz_haendler']=true
speedwalksafety['aloz_haf']=true
speedwalksafety['aloz_leder']=true
speedwalksafety['aloz_zlm1']=true
speedwalksafety['aloz_zlm2']=true
speedwalksafety['aloz_post']=true
speedwalksafety['aloz_werkzeug']=true
speedwalksafety['anl_camp']=true
speedwalksafety['anl_jas']=true
speedwalksafety['anl_run']=true
speedwalksafety['anl_skal']=true
speedwalksafety['anl_tempel']=true
speedwalksafety['anl_tief']=true
speedwalksafety['anl_toe']=true
speedwalksafety['apf_alo']=true
speedwalksafety['apf_ash']=true
speedwalksafety['apf_cor']=true
speedwalksafety['apf_min']=true
speedwalksafety['apf_teich']=true
speedwalksafety['apf_zwerge']=true
speedwalksafety['ash_alo']=true
speedwalksafety['ash_apf']=true
speedwalksafety['ash_form']=true
speedwalksafety['ash_min']=true
speedwalksafety['ash_san']=true
speedwalksafety['ash_teich']=true
speedwalksafety['ash_zwerge']=true
speedwalksafety['ashz_therme']=true
speedwalksafety['ashz_bank']=true
speedwalksafety['ashz_gast']=true
speedwalksafety['ashz_haendler']=true
speedwalksafety['ashz_lotterie']=true
speedwalksafety['ashz_zlm']=true
speedwalksafety['ashz_makler']=true
speedwalksafety['ashz_post']=true
speedwalksafety['ashz_wlm']=true
speedwalksafety['aug_bank']=true
speedwalksafety['aug_troph']=true
speedwalksafety['baecker_aloz']=true
speedwalksafety['bank_aloz']=true
speedwalksafety['bank_ashz']=true
speedwalksafety['bank_aug']=true
speedwalksafety['bank_corz']=true
speedwalksafety['bank_dhun2']=true
speedwalksafety['bank_haendler']=true
speedwalksafety['bank_ilme']=true
speedwalksafety['bank_jas']=true
speedwalksafety['bank_jer']=true
speedwalksafety['bank_min']=true
speedwalksafety['bank_skal']=true
speedwalksafety['bank_umi']=true
speedwalksafety['bank_us']=true
speedwalksafety['bank_yol']=true
speedwalksafety['barde_mio']=true
speedwalksafety['barde_ril']=true
speedwalksafety['barde_skal']=true
speedwalksafety['barde_tin']=true
speedwalksafety['barde_tol']=true
speedwalksafety['bote_mio']=true
speedwalksafety['camp_anl']=true
speedwalksafety['camp_druide']=true
speedwalksafety['camp_kap']=true
speedwalksafety['camp_kap']=true
speedwalksafety['camp_see']=true
speedwalksafety['camp_skal']=true
speedwalksafety['camp_tempel']=true
speedwalksafety['camp_tief']=true
speedwalksafety['camp_ts']=true
speedwalksafety['camp_uw']=true
speedwalksafety['cor_alo']=true
speedwalksafety['cor_apf']=true
speedwalksafety['cor_min']=true
speedwalksafety['cor_san']=true
speedwalksafety['cor_teich']=true
speedwalksafety['cor_zwerge']=true
speedwalksafety['corz_bank']=true
speedwalksafety['corz_haendler']=true
speedwalksafety['corz_haf']=true
speedwalksafety['corz_zlm']=true
speedwalksafety['corz_post']=true
speedwalksafety['corz_wlm']=true
speedwalksafety['dhun_haf']=true
speedwalksafety['dhun_min']=true
speedwalksafety['dhun_nuel']=true
speedwalksafety['dhun_uw']=true
speedwalksafety['dhun_wlm1']=true
speedwalksafety['dhun_wlm2']=true
speedwalksafety['dhun_zwerge']=true
speedwalksafety['dhun0_haendler']=true
speedwalksafety['dhun0_schmied']=true
speedwalksafety['dhun2_bank']=true
speedwalksafety['dhun2_gast']=true
speedwalksafety['dhun2_haendler']=true
speedwalksafety['dhun2_post']=true
speedwalksafety['dhun3_zlm']=true
speedwalksafety['dhun3_wlm1']=true
speedwalksafety['dhun3_wlm2']=true
speedwalksafety['dol_druide']=true
speedwalksafety['dol_haf']=true
speedwalksafety['druide_camp']=true
speedwalksafety['druide_dol']=true
speedwalksafety['druide_tol']=true
speedwalksafety['dturm_yol']=true
speedwalksafety['form_ash']=true
speedwalksafety['form_tol']=true
speedwalksafety['gast_aloz']=true
speedwalksafety['gast_haf']=true
speedwalksafety['gast_min']=true
speedwalksafety['gast_ashz']=true
speedwalksafety['gast_dhun2']=true
speedwalksafety['gol_mio']=true
speedwalksafety['gwen_haendler']=true
speedwalksafety['gwen_haf']=true
speedwalksafety['gwen_jagd']=true
speedwalksafety['gwen_zlm']=true
speedwalksafety['gwen_schmied']=true
speedwalksafety['gwen_siedlung']=true
speedwalksafety['gwen_tin']=true
speedwalksafety['haendler_aloz']=true
speedwalksafety['haendler_ashz']=true
speedwalksafety['haendler_corz']=true
speedwalksafety['haendler_dhun0']=true
speedwalksafety['haendler_dhun2']=true
speedwalksafety['haendler_gwen']=true
speedwalksafety['haendler_ilme']=true
speedwalksafety['haendler_jas']=true
speedwalksafety['haendler_jas']=true
speedwalksafety['haendler_jer']=true
speedwalksafety['haendler_min']=true
speedwalksafety['haendler_mio']=true
speedwalksafety['haendler_bank']=true
speedwalksafety['haendler_skal']=true
speedwalksafety['haendler_us']=true
speedwalksafety['haendler_yol']=true
speedwalksafety['haf_aloz']=true
speedwalksafety['haf_corz']=true
speedwalksafety['haf_dhun']=true
speedwalksafety['haf_dol']=true
speedwalksafety['haf_gast']=true
speedwalksafety['haf_gwen']=true
speedwalksafety['haf_ilme']=true
speedwalksafety['haf_jas']=true
speedwalksafety['haf_jer']=true
speedwalksafety['haf_lim']=true
speedwalksafety['haf_min']=true
speedwalksafety['haf_sol']=true
speedwalksafety['haf_tol']=true
speedwalksafety['haf_umi']=true
speedwalksafety['haf_ver']=true
speedwalksafety['haf_vul']=true
speedwalksafety['haf2_umi']=true
speedwalksafety['ilme_bank']=true
speedwalksafety['ilme_haendler']=true
speedwalksafety['ilme_haf']=true
speedwalksafety['ilme_zlm1']=true
speedwalksafety['ilme_zlm2']=true
speedwalksafety['ilme_post']=true
speedwalksafety['ilme_tol']=true
speedwalksafety['ilme_uw']=true
speedwalksafety['ilme_wlm1']=true
speedwalksafety['ilme_wlm2']=true
speedwalksafety['jagd_gwen']=true
speedwalksafety['jagd_tin']=true
speedwalksafety['jas_alch']=true
speedwalksafety['jas_anl']=true
speedwalksafety['jas_bank']=true
speedwalksafety['jas_haendler']=true
speedwalksafety['jas_haf']=true
speedwalksafety['jas_zlm']=true
speedwalksafety['jas_nekro']=true
speedwalksafety['jas_post']=true
speedwalksafety['jas_schmied']=true
speedwalksafety['jas_tempel']=true
speedwalksafety['jas_tempel']=true
speedwalksafety['jas_uw']=true
speedwalksafety['jer_bank']=true
speedwalksafety['jer_haendler']=true
speedwalksafety['jer_haf']=true
speedwalksafety['jer_zlm']=true
speedwalksafety['jer_ver']=true
speedwalksafety['kap_camp']=true
speedwalksafety['kap_camp']=true
speedwalksafety['kap_ril']=true
speedwalksafety['kap_tempel']=true
speedwalksafety['kap_uw']=true
speedwalksafety['ker_troph']=true
speedwalksafety['ker_wlm']=true
speedwalksafety['leder_aloz']=true
speedwalksafety['lederer_mio']=true
speedwalksafety['lim_haf']=true
speedwalksafety['lotterie_ashz']=true
speedwalksafety['zlm_ashz']=true
speedwalksafety['zlm_corz']=true
speedwalksafety['zlm_dhun3']=true
speedwalksafety['zlm_gwen']=true
speedwalksafety['zlm_jas']=true
speedwalksafety['zlm_jer']=true
speedwalksafety['zlm_ril']=true
speedwalksafety['zlm_skal']=true
speedwalksafety['zlm1_aloz']=true
speedwalksafety['zlm1_ilme']=true
speedwalksafety['zlm_min']=true
speedwalksafety['zlm1_tol']=true
speedwalksafety['zlm2_aloz']=true
speedwalksafety['zlm2_ilme']=true
speedwalksafety['zlm1_mio']=true
speedwalksafety['zlm2_tol']=true
speedwalksafety['zlm2_mio']=true
speedwalksafety['makler_ashz']=true
speedwalksafety['min_alo']=true
speedwalksafety['min_apf']=true
speedwalksafety['min_ash']=true
speedwalksafety['min_bank']=true
speedwalksafety['min_cor']=true
speedwalksafety['min_dhun']=true
speedwalksafety['min_gast']=true
speedwalksafety['min_haendler']=true
speedwalksafety['min_haf']=true
speedwalksafety['min_zlm']=true
speedwalksafety['min_mio']=true
speedwalksafety['min_post']=true
speedwalksafety['min_quelle']=true
speedwalksafety['min_san']=true
speedwalksafety['min_schmied']=true
speedwalksafety['min_teich']=true
speedwalksafety['min_uw']=true
speedwalksafety['min_wlm']=true
speedwalksafety['min_zwerge']=true
speedwalksafety['mio_barde']=true
speedwalksafety['mio_bote']=true
speedwalksafety['mio_gol']=true
speedwalksafety['mio_haendler']=true
speedwalksafety['mio_lederer']=true
speedwalksafety['mio_min']=true
speedwalksafety['mio_stadtwache']=true
speedwalksafety['mio_wlm1']=true
speedwalksafety['mio_wlm2']=true
speedwalksafety['mio_zlm1']=true
speedwalksafety['mio_zlm2']=true
speedwalksafety['mine_por']=true
speedwalksafety['mine_tin']=true
speedwalksafety['mine_us']=true
speedwalksafety['nekro_jas']=true
speedwalksafety['nekro_uw']=true
speedwalksafety['nuel_dhun']=true
speedwalksafety['nuel_uw']=true
speedwalksafety['nuel_zwerge']=true
speedwalksafety['por_mine']=true
speedwalksafety['por_ril']=true
speedwalksafety['por_uw']=true
speedwalksafety['post_aloz']=true
speedwalksafety['post_ashz']=true
speedwalksafety['post_corz']=true
speedwalksafety['post_dhun2']=true
speedwalksafety['post_ilme']=true
speedwalksafety['post_jas']=true
speedwalksafety['post_min']=true
speedwalksafety['post_ril']=true
speedwalksafety['post_skal']=true
speedwalksafety['quelle_min']=true
speedwalksafety['quelle_san']=true
speedwalksafety['ril_barde']=true
speedwalksafety['ril_kap']=true
speedwalksafety['ril_zlm']=true
speedwalksafety['ril_por']=true
speedwalksafety['ril_post']=true
speedwalksafety['ril_wlm']=true
speedwalksafety['run_anl']=true
speedwalksafety['san_alo']=true
speedwalksafety['san_ash']=true
speedwalksafety['san_cor']=true
speedwalksafety['san_min']=true
speedwalksafety['san_quelle']=true
speedwalksafety['san_zwerge']=true
speedwalksafety['schmied_dhun0']=true
speedwalksafety['schmied_gwen']=true
speedwalksafety['schmied_jas']=true
speedwalksafety['schmied_min']=true
speedwalksafety['schmied_siedlung']=true
speedwalksafety['schmied_skal']=true
speedwalksafety['schmied_sol']=true
speedwalksafety['schmied_tol']=true
speedwalksafety['schmied_yol']=true
speedwalksafety['see_camp']=true
speedwalksafety['see_tief']=true
speedwalksafety['siedlung_gwen']=true
speedwalksafety['siedlung_schmied']=true
speedwalksafety['siedlung_tin']=true
speedwalksafety['skal_anl']=true
speedwalksafety['skal_bank']=true
speedwalksafety['skal_barde']=true
speedwalksafety['skal_camp']=true
speedwalksafety['skal_haendler']=true
speedwalksafety['skal_zlm']=true
speedwalksafety['skal_post']=true
speedwalksafety['skal_schmied']=true
speedwalksafety['skal_tief']=true
speedwalksafety['skal_troph']=true
speedwalksafety['skal_uw']=true
speedwalksafety['skal_wlm1']=true
speedwalksafety['skal_wlm2']=true
speedwalksafety['slm_us']=true
speedwalksafety['sol_haf']=true
speedwalksafety['sol_schmied']=true
speedwalksafety['stadtwache_mio']=true
speedwalksafety['teich_alo']=true
speedwalksafety['teich_apf']=true
speedwalksafety['teich_ash']=true
speedwalksafety['teich_cor']=true
speedwalksafety['teich_min']=true
speedwalksafety['teich_uw']=true
speedwalksafety['teich_zwerge']=true
speedwalksafety['tempel_anl']=true
speedwalksafety['tempel_camp']=true
speedwalksafety['tempel_jas']=true
speedwalksafety['tempel_kap']=true
speedwalksafety['tempel_uw']=true
speedwalksafety['therme_ashz']=true
speedwalksafety['tief_anl']=true
speedwalksafety['tief_camp']=true
speedwalksafety['tief_see']=true
speedwalksafety['tief_skal']=true
speedwalksafety['tin_barde']=true
speedwalksafety['tin_gwen']=true
speedwalksafety['tin_jagd']=true
speedwalksafety['tin_mine']=true
speedwalksafety['tin_siedlung']=true
speedwalksafety['tin_wl']=true
speedwalksafety['toe_anl']=true
speedwalksafety['toe_yol']=true
speedwalksafety['tol_barde']=true
speedwalksafety['tol_druide']=true
speedwalksafety['tol_form']=true
speedwalksafety['tol_haf']=true
speedwalksafety['tol_ilme']=true
speedwalksafety['tol_zlm1']=true
speedwalksafety['tol_zlm2']=true
speedwalksafety['tol_schmied']=true
speedwalksafety['troph_aug']=true
speedwalksafety['troph_ker']=true
speedwalksafety['troph_skal']=true
speedwalksafety['troph_us']=true
speedwalksafety['ts_camp']=true
speedwalksafety['umi_bank']=true
speedwalksafety['umi_haf']=true
speedwalksafety['umi_haf2']=true
speedwalksafety['umi_wlm']=true
speedwalksafety['us_bank']=true
speedwalksafety['us_haendler']=true
speedwalksafety['us_mine']=true
speedwalksafety['us_slm']=true
speedwalksafety['us_troph']=true
speedwalksafety['us_zwerge']=true
speedwalksafety['uw_camp']=true
speedwalksafety['uw_dhun']=true
speedwalksafety['uw_ilme']=true
speedwalksafety['uw_jas']=true
speedwalksafety['uw_kap']=true
speedwalksafety['uw_min']=true
speedwalksafety['uw_nekro']=true
speedwalksafety['uw_nuel']=true
speedwalksafety['uw_por']=true
speedwalksafety['uw_skal']=true
speedwalksafety['uw_teich']=true
speedwalksafety['uw_tempel']=true
speedwalksafety['uw_zwerge']=true
speedwalksafety['ver_haf']=true
speedwalksafety['ver_jer']=true
speedwalksafety['vul_haf']=true
speedwalksafety['werkzeug_aloz']=true
speedwalksafety['wl_tin']=true
speedwalksafety['wlm_ashz']=true
speedwalksafety['wlm_corz']=true
speedwalksafety['wlm_ker']=true
speedwalksafety['wlm_ril']=true
speedwalksafety['wlm1_skal']=true
speedwalksafety['wlm2_skal']=true
speedwalksafety['wlm_umi']=true
speedwalksafety['wlm1_dhun']=true
speedwalksafety['wlm2_dhun']=true
speedwalksafety['wlm1_dhun3']=true
speedwalksafety['wlm1_ilme']=true
speedwalksafety['wlm_min']=true
speedwalksafety['wlm2_dhun3']=true
speedwalksafety['wlm2_ilme']=true
speedwalksafety['wlm1_mio']=true
speedwalksafety['wlm2_mio']=true
speedwalksafety['yol_bank']=true
speedwalksafety['yol_dturm']=true
speedwalksafety['yol_haendler']=true
speedwalksafety['yol_schmied']=true
speedwalksafety['yol_toe']=true
speedwalksafety['zwerge_alo']=true
speedwalksafety['zwerge_apf']=true
speedwalksafety['zwerge_ash']=true
speedwalksafety['zwerge_cor']=true
speedwalksafety['zwerge_dhun']=true
speedwalksafety['zwerge_min']=true
speedwalksafety['zwerge_nuel']=true
speedwalksafety['zwerge_san']=true
speedwalksafety['zwerge_teich']=true
speedwalksafety['zwerge_us']=true
speedwalksafety['zwerge_uw']=true
